### ISSUE TITLE
Crash When Loading Too Many Chunks?

### ISSUE THREAD

**Issue by WPGCentral** [Johni0702/bobby#10]
`---- Minecraft Crash Report ----
// Don't do that.

Time: 2/19/21 8:44 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
	at net.minecraft.world.World.redirect$bmf000$checkProcessTEs(World:5753)
	at net.minecraft.world.World.tickBlockEntities(World:504)
	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:176)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1531)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:996)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
	All players: 1 total; [class_746['WyattPlayzMC'/2519759, l='ClientLevel', x=-139.38, y=128.73, z=105.02]]
	Chunk stats: SodiumChunkCache: 121 F: 443 M: 525 L: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (2840,138,1343), Chunk: (at 8,8,15 in 177,83; contains blocks 2832,0,1328 to 2847,255,1343), Region: (5,2; contains chunks 160,64 to 191,95, blocks 2560,0,1024 to 3071,255,1535)
	Level time: 65755 game time, 224004058 day time
	Server brand: Waterfall <- §9TechMedia Server Core§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$zhg000$onCrash(class_310.java:5352)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3615982944 bytes (3448 MB) / 5368709120 bytes (5120 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Fabric Loader (fabricloader)
	Fabric Mods: 
		advancedchat: AdvancedChat 2.1.0
		advancednbttooltip: Advanced NBT Tooltips 1.0.5
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		auto_third_person: Auto Third Person 1.1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bbor: BoundingBoxOutlineReloaded 2.4-1.16.3
		betterpingdisplay: Better Ping Display 1.1
		blue_endless_jankson: jankson 1.2.0
		bobby: Bobby 0.2.0
		branding: Branding 1.0.0
		carpet: Carpet Mod in Fabric 1.4.12
		carpet-extra: Carpet Extra 1.4.27
		chatcalc: ChatCalc 2.2
		chesttracker: Chest Tracker 0.7.11
		clientcommands: Client Commands 2.4.7
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cmdkeybind: Command Macros 1.5.0-1.16
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		completeconfig: CompleteConfig 0.9.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		customwindowtitle: Custom Window Title 1.1.0
		dontdropit: Don't Drop It! 2.1.0+1.16
		dynamicfps: Dynamic FPS 2.0.1
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.3
		fabric: Fabric API 0.25.0+build.415-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.6+build.214
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.4-1.16
		libgui: LibGui 3.2.2+1.16.3
		lionutils: LionUtils 6.0.1+1.16
		litematica: Litematica 0.0.0-dev.20200913.215807
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.3
		minihud: MiniHUD 0.19.0-dev.20200912.222204
		mobcountmod: MobCountMod 1.6.0-dev.20201204.233518
		modmenu: Mod Menu 1.14.6+build.31
		multiconnect-api: MultiConnect API 1.3.9
		notenoughcrashes: Not Enough Crashes 3.1.5
		phosphor: Phosphor 0.6.0+build.7
		player_events: Player Events 2.0.0
		player_events_api: Player Events API 2.0.0
		quickcraft: Quickcraft 1.2.4
		rad: Reload Audio Driver 1.0.1
		randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
		signsearcher: Sign Searcher 0.2.1+mc1.16.3
		sodium: Sodium 0.1.0
		spark: spark 1.4.3
		torohealth: ToroHealth Damage Indicators 1.16.3-fabric-4
		tweakeroo: Tweakeroo 0.10.0-dev.20210209.145902
		uglyscoreboardfix: Ugly Scoreboard Fix 1.1.0
		usefulutilities: Useful Utilities 1.4.2
		xaerominimap: Xaero's Minimap 20.29.1
		xaeroworldmap: Xaero's World Map 1.11.4
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: bbor (incompatible), vanilla, file/NoteBlocks, file/Meme, fabric/advancedchat, fabric/amecsapi, fabric/autoconfig1u, fabric/bbor, fabric/betterpingdisplay, fabric/carpet, fabric/chesttracker, fabric/clientcommands (incompatible), fabric/cloth-config2, fabric/cmdkeybind, fabric/dontdropit, fabric/dynamicfps, fabric/easiervillagertrading, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-command-api-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/jankson, fabric/libgui, fabric/lionutils, fabric/litematica (incompatible), fabric/lithium, fabric/malilib (incompatible), fabric/minihud (incompatible), fabric/mobcountmod (incompatible), fabric/modmenu, fabric/multiconnect-api, fabric/phosphor, fabric/player_events, fabric/player_events_api, fabric/quickcraft, fabric/rad, fabric/randompatches, fabric/signsearcher, fabric/sodium, fabric/tweakeroo (incompatible), fabric/uglyscoreboardfix, fabric/xaerominimap, fabric/xaeroworldmap
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0`

Got this crash a few times when I loaded possibly a few too many chunks? I am not sure why, but removing the mod resulted in no more crashes. There came a point where every time I joined the server, I would get a crash. I even attempted to compile the source for my minecraft version (1.16.3), but that too resulted in the same crash.

**Comment by Johni0702** [comment]
I don't think this is caused by Bobby. It's probably just more likely to happen the more chunks are loaded.
At least there's a mention of the exact issue in Carpet's source since almost a year before bobby even existed: https://github.com/gnembon/fabric-carpet/commit/7f09bbf1938ce2779d3d2cd45cee003c0f6305d6
So I'm guessing this is either a bug in MC itself (though looking at it for a while, I couldn't find anything) or it is caused by some third-party mod. I suggest you try narrowing it down by throwing out half of them at a time. If you crash, repeat the process with that half, otherwise try the other half.

**Comment by WPGCentral** [comment]
I can confirm that it is _not_ a third party mod I had installed as I just tested it again with the only mod being installed was bobby. I get kicked to a screen that says "Saving World" and crashed with "unexpected error".

**Comment by Johni0702** [comment]
Please post an updated crash report (or log file). The one above is literally impossible without carpet.

**Comment by WPGCentral** [comment]
`---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/20/21 9:06 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_1937.method_18471(class_1937.java:504)
	at net.minecraft.class_638.method_18116(class_638.java:176)
	at net.minecraft.class_310.method_1574(class_310.java:1531)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:504)
	at net.minecraft.class_638.method_18116(class_638.java:176)

-- Affected level --
Details:
	All players: 4 total; [class_746['WyattPlayzMC'/2168443, l='ClientLevel', x=67.30, y=267.09, z=58.39], class_745['PhilpPhlip'/2181093, l='ClientLevel', x=48.89, y=68.00, z=55.85], class_745['Sb3ve'/2048846, l='ClientLevel', x=71.07, y=67.00, z=51.89], class_745['endermenfight49'/2159410, l='ClientLevel', x=47.75, y=68.00, z=56.78]]
	Chunk stats: Client Chunk Cache: 225, 121 F: 3419 M: 685 L: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (2840,138,1343), Chunk: (at 8,8,15 in 177,83; contains blocks 2832,0,1328 to 2847,255,1343), Region: (5,2; contains chunks 160,64 to 191,95, blocks 2560,0,1024 to 3071,255,1535)
	Level time: 133964 game time, 224840267 day time
	Server brand: Waterfall <- §9TechMedia Server Core§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 724746488 bytes (691 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.10.6+build.214-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz`

**Comment by Johni0702** [comment]
I have posted a potential fix in #14.
Since I cannot reproduce the issue, please give that version a try and report back on whether it fixes the issue for you.
