### ISSUE TITLE
Bobby crashing the game

### ISSUE THREAD

**Issue by ramblade** [Johni0702/bobby#102]
For some context i updated my game and mods to 1.19 last night and when i started playing today i noticed after flying around on a server for a small while my game unexpectedly crashes. After testing my mods it seems like removing bobby fixed the problem.

Crash Report: https://paste.gg/p/anonymous/175619bac17b4a7e846798acfe77891a

**Comment by Johni0702** [comment]
Do you have some way to reliably reproduce this issue? If so, could you please make sure it's not some kind of cross-mod interaction by removing as many third-party mods as possible?

**Comment by ramblade** [comment]
I think i accidentally fixed this bug by updating some of my mods,
