### ISSUE TITLE
Crash with Bobby when joining Servers

### ISSUE THREAD

**Issue by ListerWorks** [Johni0702/bobby#105]
Updated to 14.8-1.19 Fabric Loader and tried using the Bobby 4.0 but it crashes with a divisible by 0 java error. Doesnt crash on a Single Player World. Tried joining a 1.19 server and a 1.18.2 server that allows 1.19 clients to join.
Time: 7/12/22, 7:46 PM
--
  | Description: Unexpected error
  |  
  | java.lang.ArithmeticException: / by zero
  | at net.minecraft.class_310.handler$zzf000$bobbyUpdate(class_310.java:2889)
  | at net.minecraft.class_310.method_1523(class_310.java:1098)
  | at net.minecraft.class_310.method_1514(class_310.java:734)
  | at net.minecraft.client.main.Main.main(Main.java:237)
  | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
  | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
  | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java

https://paste.gg/p/anonymous/647be6f4141b4343be367e3bd9269e7d

**Comment by CanadianJen** [comment]
same problem - crashing when I use Bobby on a 1.19 server. (I'm using a Apple M1 - not sure if that has anything to do with it) 

Description: Unexpected error
--
  |  
  | java.lang.ArithmeticException: / by zero
  | at net.minecraft.class_310.handler$zzf000$bobbyUpdate(class_310.java:2889)
  | at net.minecraft.class_310.method_1523(class_310.java:1098)
  | at net.minecraft.class_310.method_1514(class_310.java:734)
  | at net.minecraft.client.main.Main.main(Main.java:237)
  | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
  | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
  | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  | at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
  | at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
  | at org.multimc.EntryPoint.listen(EntryPoint.java:143)
  | at org.multimc.EntryPoint.main(EntryPoint.java:34)

https://paste.gg/p/anonymous/d806276fe2c042c2b5f1823938afa4b0

**Comment by Johni0702** [comment]
Could one of you please attach your `options.txt` file?
And **then** please try without Optifine.
And if that doesn't help, try changing your Max Framerate setting. Based on the error it's 0, but that's not a valid value.

**Comment by Random-Humanoid** [comment]
Changing the Max Framerate to above vsync solves the crashing issue.

**Comment by CanadianJen** [comment]
https://paste.gg/p/anonymous/150e0aee95d44a32853b3673472bcc74 

It is working without Optifine and Optifabric. Tested on both a Paper and a Fabric server - logged in beautifully!

**Comment by drathmorgh** [comment]
I can confirm that Vsync is crashing the game! 
I have a 12900k 3080ti win 11... works beautifully until I drop it down to Vsync and crash!

**Comment by Johni0702** [comment]
Report this to Optifine then. It must not set the maxFramerate to 0, that's not a valid value.
