### ISSUE TITLE
Bobby has no configure menu

### ISSUE THREAD

**Issue by GlassOFMilk2** [Johni0702/bobby#106]
I downloaded bobby with a couple of other mods including mod menu. and there is no way for me to configure bobby to run on the game. the mods i have are 
-  Bobby-4.0.0
-  cloth-config-7.0.73-forge
-  Fabric-api-0.57.0+1.19
-  Iris-mc1.19-1.2.5
-  logical_zoom-0.0.15
-  modmenu-4.0.4
-  sodium-fabric-mc1.19-0.4.2+build.16
im new to this so i dont know what im supposed to do

**Comment by Johni0702** [comment]
You installed the Forge version of ClothConfig, that won't load on Fabric. You need to install the Fabric version.
