### ISSUE TITLE
Render distance resets to 12 when opening game

### ISSUE THREAD

**Issue by alexandraflynn0** [Johni0702/bobby#109]
When opening the game, if render distance was previously set above 32, then the render distance is reset to 12. It doesn't seem to depend on what exactly the render distance or max render distance were set to, only if render distance was above 32. I tested it on a fresh 1.19 instance with only Bobby, Cloth Config, and Mod Menu installed. I've had the issue on two different computers. Has anyone else noticed this or is it just on my end? Thanks!

**Comment by alexandraflynn0** [comment]
[latest.log](https://github.com/Johni0702/bobby/files/9194104/latest.log)


This line looks interesting: 
[19:42:46] [Render thread/ERROR]: Error parsing option value 48 for option Render Distance: Value 48 outside of range [2:33]

(Also, small oversight, forgot to install Sodium on my test instance at first)

**Comment by Julienraptor01** [comment]
> [latest.log](https://github.com/Johni0702/bobby/files/9194104/latest.log)
> 
> This line looks interesting: [19:42:46] [Render thread/ERROR]: Error parsing option value 48 for option Render Distance: Value 48 outside of range [2:33]
> 
> (Also, small oversight, forgot to install Sodium on my test instance at first)

this may be due to vanilla limitation to block values outside of expected range
you should try to add that mod to confirm my theory
https://modrinth.com/mod/fiveonefouroneeight
this mod remove the patch mojang added to prevent the values

**Comment by alexandraflynn0** [comment]
This fixes it, thank you! So it's not a problem with Bobby after all

**Comment by Julienraptor01** [comment]
> This fixes it, thank you! So it's not a problem with Bobby after all

It is a problem with Bobby, the problem is that Bobby doesn't patch the value range

What Bobby should do is change the expected value range accordingly to the capabilities of the mod so that the game doesn't see an unexpected value and mojang patch don't need to be removed

@Johni0702 I found the exact issue

**Comment by Johni0702** [comment]
Bobby does patch the value (otherwise you wouldn't be able to go able 32 in the settings menu either) but only after the settings have already been loaded from the file. A different, second patch is required to fix this in time for loading.

**Comment by Julienraptor01** [comment]
> Bobby does patch the value (otherwise you wouldn't be able to go above 32 in the settings menu either) but only after the settings have already been loaded from the file. A different, second patch is required to fix this in time for loading.

Yeah it's what i meant sorry if i was unclear, it need an earlier patch

**Comment by fibrowolf** [comment]
i have same issue , defaults to servers render even though it says larger amount in bobby

**Comment by Julienraptor01** [comment]
> i have same issue , defaults to servers render even though it says larger amount in bobby

I gave a temporary solution above while waiting for a fix to be implemented

**Comment by fibrowolf** [comment]
the temp fix works

**Comment by fibrowolf** [comment]
the temp fix seamed to work , but it doesnt, its stuck at world render distance

**Comment by Julienraptor01** [comment]
> the temp fix seamed to work , but it doesnt, its stuck at world render distance

What do you mean by world render distance ? Like the world (server) distance is ex 16 and your client distance is 32 but you still only see 16 ?

**Comment by fibrowolf** [comment]
yes the render is 16 on server and i have tried 32, 64, 128 and 256 and they all stay at 16
