### ISSUE TITLE
Map of saved chunks.

### ISSUE THREAD

**Issue by Esper89** [Johni0702/bobby#11]
It would be easier to see which chunks have been saved and which still need to be loaded if there were an in-game map of all the saved chunks, similar to [mircokroon/minecraft-world-downloader](https://github.com/mircokroon/minecraft-world-downloader)'s map.

**Comment by Johni0702** [comment]
Just installing any old minimap mod (as long as it also has a world map) should do that.

If you have installed both, Bobby and the minimap mod, from the beginning, they will both save any chunk which you received, so the data they store will cover the same area and you can effectively use the world map to see which chunks bobby knows of.

If you've already used Bobby for a while and are adding the minimap now, you could probably just look straight down (so it does not actually render everything), crank the render distance up to 256 chunks and populate the minimap mod that way (might not work depending on how the minimap mod is implemented; also requires a bit of RAM).

Having Bobby serve its own world map seems way out of scope (cause at that point it would effectively be a minimap mod), so I'm closing this feature request. If you're having trouble using it with a minimap/worldmap mod, feel free to open another issue for that.
