### ISSUE TITLE
Wynncraft multiplayer

### ISSUE THREAD

**Issue by Stevn2688** [Johni0702/bobby#114]
Bobby 1.19.2 won't work in multiplayer. Singleplayer is perfect. Tried in 1.17 as well, no difference. In .bobby folder the ip is correct.

**Comment by Johni0702** [comment]
Do you have any other mods installed that may prevent it from functioning? I wrote this mod for my own use on Wynncraft, so unless they changed something recently, it should definitely work on there.

**Comment by Johni0702** [comment]
I played a whole bunch of Wynncraft on 1.19.2 recently with no issues whatsoever. Closing this due to lack of response and inability to reproduce.
