### ISSUE TITLE
Not compatible with Terra++ mod?

### ISSUE THREAD

**Issue by TheCheekiBreekiest** [Johni0702/bobby#119]
Using Minecraft Iris for 1.18.2. Max view distance (32 chunks), 64 chunks in bobby distance. Terrain still disappears after a certain distance as if it were vanilla Iris. Chunks are apparently being saved to .bobby

https://user-images.githubusercontent.com/93954526/202551723-467fc23b-8bea-4c26-a6ff-866b2826dfa2.mp4

**Comment by Johni0702** [comment]
Your video shows that your render distance is set to 32, so you're getting 32 chunks worth to see and no more. There is no "bobby distance". If you want more than 32, you have to increase the max in bobby's config and then drag that slider further.
![](https://i.johni0702.de/dEeg6.png)
