### ISSUE TITLE
Doesn't work in the nether

### ISSUE THREAD

**Issue by xpopy** [Johni0702/bobby#12]
The mod doesn't seem to save the chunks in the nether. Havent tested the end but i assume it's the same issue there

In case this is intentional, could we get an option to turn on/off specific worlds?

**Comment by Johni0702** [comment]
It does. If it does not for you, you'll have to provide more information.
![](https://i.johni0702.de/3UUdx.png)

**Comment by xpopy** [comment]
Ah sorry, was an issue with sodium where fog occlusion was enabled but fog was disabled.
