### ISSUE TITLE
4.0.1 still only showing server render distance

### ISSUE THREAD

**Issue by fibrowolf** [Johni0702/bobby#120]
i haven't changed any other mods, even tried on its own and it still only shows server render distance and doesnt save the chunks you have loaded already beyond that distance

**Comment by fibrowolf** [comment]
i have tried a new instance with just bobby in, there are no error messages either

**Comment by Johni0702** [comment]
That's not even remotely enough information for me to help you with anything. Clearly it works for other people (including myself) so there must be something you're doing that everyone else doesn't or something everyone does that you aren't.
Let's start by taking a screenshot of your F3 screen to check that it's even installed and not disabled.

**Comment by fibrowolf** [comment]
ok so i found a way to make it work, but i had to turn up the game render distance to 64 and then the files are kept by bobby
