### ISSUE TITLE
Singleplayer load from world save as bobby cache 

### ISSUE THREAD

**Issue by KidOfCubes** [Johni0702/bobby#122]
Would it be possible to read chunks into bobby out of the integrated server view range from the region files in my world save? So I could have over 32 render distance in my singleplayer world without having to go everywhere to cache it first (the chunks are already generated, they're just not in the bobby cache and wont load)?

**Comment by Johni0702** [comment]
Bobby's cache file format is a subset of Minecraft's save file format, so you can just copy over all the `mca` files from `.minecraft/saves/<WorldName>/region/` to `.minecraft/.bobby/<WorldName>/<HashedSeed>/minecraft/overworld/` (and optionally `<WorldName>/DIM1/region/` to `minecraft/the_nether/` and `<WorldName>/DIM-1/region/` to `minecraft/the_end/`).
