### ISSUE TITLE
After crash, Cannot enter nether

### ISSUE THREAD

**Issue by Angryfishdonut** [Johni0702/bobby#127]
When I do, I am in unloaded chunks, I see the overworld in the distance and I cannot move

video showcasing the issue
https://youtu.be/LEy2wicOxqs

**Comment by Johni0702** [comment]
Please attach the `.minecraft/logs/latest.log` file after you've tried to enter the nether.

**Comment by Angryfishdonut** [comment]
[latest.log](https://github.com/Johni0702/bobby/files/10342016/latest.log)
Here You go. Sorry for taking so long, didn't have access to my PC

Btw, why is it called bobby if you're not named bobby?? (judging by your username)

**Comment by Johni0702** [comment]
That's not the right log, it just has optifine and nothing else, no bobby, no errors.

> Btw, why is it called bobby if you're not named bobby?? (judging by your username)

I couldn't come up with any good name and so I made the mistake of asking for name suggestions and that, well, didn't really work either.

**Comment by Angryfishdonut** [comment]
OK, I found the right one. 

You can see the chat visible in the video on line 7433

[2022-12-30-4.log](https://github.com/Johni0702/bobby/files/10367604/2022-12-30-4.log)
![chat](https://user-images.githubusercontent.com/72036928/211178414-073af422-db6e-4163-9270-0b854dd5997e.PNG)

**Comment by Johni0702** [comment]
It's #92. If you've made a backup before deleting all the chunk data, you can restore that and only delete the `last_access` file, which doesn't contain any critical data (just means that if you use the "Delete after X days" option, chunks will stay around for a bit longer than they should).
Closing as duplicate.
