### ISSUE TITLE
Are 32+ render distances supported on both multiplayer and singleplayer?

### ISSUE THREAD

**Issue by RaptaG** [Johni0702/bobby#129]

**Comment by RaptaG** [comment]
@Johni0702 ?

**Comment by Johni0702** [comment]
Yes?
There isn't actually any technical difference between SP and MP as far as the main functionality of bobby and sodium are concerned. SP internally also just run an integrated server, so it's basically just MP without the option for others to join (until you click the Open To LAN button).
