### ISSUE TITLE
doesnt work on realms

### ISSUE THREAD

**Issue by rodrigogoc** [Johni0702/bobby#130]

**Comment by Johni0702** [comment]
define "doesn't work"
Do chunks unload immediately after leaving server view-distance?
Do distant chunks you've visited before not load when you increase your render distance?
Do distant chunks you've visited before not load when changing dimension?
Do distant chunks you've visited before not load when you reconnect?

Also, I don't have a realm to test on; if you could invite me to one (IGM matches GitHub) that'd be helpful.
