### ISSUE TITLE
No in-game config menu (1.19.3)

### ISSUE THREAD

**Issue by Abigail7200** [Johni0702/bobby#139]
Hello, I have no ingame config menu for the mod. ModMenu and ClothConfig are installed and I have ingame config menus for other mods

**Comment by Johni0702** [comment]
Please take a screenshot of the mod in modmenu without the config button.
And please also attach the `latest.log` file.

**Comment by Abigail7200** [comment]
Here's the screenshot : https://user-images.githubusercontent.com/123870687/215458616-66616ad2-05e6-4e55-917f-b428307a1393.png
And the `latest.log` https://github.com/Johni0702/bobby/files/10535078/latest.log

**Comment by Johni0702** [comment]
Based on the log, you do not have ClothConfig installed. Make sure you've installed the Fabric version, not the Forge version.

**Comment by Abigail7200** [comment]
Yup that was it, my mistake. Shouldn't have fallen for that hehe
