### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by PotatoPresident** [Johni0702/bobby#14]
Not sure if this is related to the other 2 issues.
I _think_ it might be an indium incompatibility.
[https://paste.ee/p/SCU9R](https://paste.ee/p/SCU9R)

**Comment by Johni0702** [comment]
Yes, pretty sure this is the same bug as #10 but the crash is in a different, easier to understand place.
Please give this version a try and report back on whether it fixes the issue for you (assuming you can somewhat reliably reproduce it): https://i.johni0702.de/bobby-1.1.0-SNAPSHOT.issue.14.jar

**Comment by Johni0702** [comment]
Duplicate of #10
