### ISSUE TITLE
Config screen not able to load

### ISSUE THREAD

**Issue by TheMCV3teran** [Johni0702/bobby#153]
idk what this is about, i just got an alert from mod menu to report this to you guys, i dont care all that much, i dont really need to config this mod, just reporting it because it's an issue/bug, i think

**Comment by Johni0702** [comment]
What version are you on?
I'm having no such issue on Minecraft 1.19.4 with Bobby 4.0.5 + ClothConfig 10.0.96 + ModMenu 6.1.0-rc4

**Comment by bwoodfield** [comment]
> What version are you on? I'm having no such issue on Minecraft 1.19.4 with Bobby 4.0.5 + ClothConfig 10.0.96 + ModMenu 6.1.0-rc4

I have the same versions of Bobby, ClothConfig, and Modmenu installed and I don't get the configuration screen either.  When I go into ModMenu and view Bobby there is only the Website, and Report Issue buttons
![2023-04-27_10 33 41](https://user-images.githubusercontent.com/17112986/234912696-51c717ec-f87b-4fe8-8adf-9a7255680bf0.png)

**Comment by Johni0702** [comment]
I'll take a guess and say you installed the Forge version of ClothConfig rather than the Fabric version.
If that's not the case, please send the `latest.log` file.

**Comment by Bloofield** [comment]
I'm also getting the same issue
[latest.log](https://github.com/Johni0702/bobby/files/11657813/latest.log)

**Comment by Johni0702** [comment]
> I'm also getting the same issue [latest.log](https://github.com/Johni0702/bobby/files/11657813/latest.log)

Same problem: You don't have ClothConfig (the fabric version!) installed.
