### ISSUE TITLE
Stuck on Joining world... screen

### ISSUE THREAD

**Issue by Evervented** [Johni0702/bobby#161]
I turned off Bobby's functionality in Mod Menu, and I was able to join the server just fine. However, if I tried to turn it back on again in Mod Menu, it wouldn't generate chunks further than the server render distance. I originally have used the singleplayer world function as a fallback to generate chunks further and leave them loaded, but now nothing loads if I reenable it while on the server, and I cannot join the server with it on. Any help would be appreciated.

**Comment by Johni0702** [comment]
Going to assume this to be the same as #92 then, which should be fixed as of v4.0.6.
