### ISSUE TITLE
How do you make Bobby work?

### ISSUE THREAD

**Issue by QueenUlyana** [Johni0702/bobby#162]
My mod doesn't work, I can't see the chunks I've loaded. What should I do?

![2023-05-28_13 08 42](https://github.com/Johni0702/bobby/assets/83131824/24207e4d-95b6-40f3-9930-e36cafa76003)
![2023-05-28_13 10 01](https://github.com/Johni0702/bobby/assets/83131824/ceec923d-d668-49ba-9b6f-d03462bed4c9)
![2023-05-28_13 10 04](https://github.com/Johni0702/bobby/assets/83131824/1ec25ac1-36fc-4238-bf9b-d269bf79d71a)
![2023-05-28_13 10 15](https://github.com/Johni0702/bobby/assets/83131824/88fcb6d0-e5ff-4af4-a0c1-24d0537e955a)

**Comment by cootshk** [comment]
it's a multiplayer mod, it doesnt work in single player
