### ISSUE TITLE
Booby doesn't show visited chuck

### ISSUE THREAD

**Issue by Revplay** [Johni0702/bobby#163]
I've set the chuck at 256 but the game still won't render chuck farther than 32
![2023-05-29_10 39 23](https://github.com/Johni0702/bobby/assets/134903798/1a05db32-aa4c-4f8c-964e-54c92713aecc)
![2023-05-29_10 39 27](https://github.com/Johni0702/bobby/assets/134903798/411fe45a-3f5b-45e1-804b-6108596d4383)
32 Chuck as reference
![2023-05-29_10 38 47](https://github.com/Johni0702/bobby/assets/134903798/cf0ee841-01bd-4265-905e-7fd59bc9688f)
![2023-05-29_10 39 09](https://github.com/Johni0702/bobby/assets/134903798/49ad67cd-9e09-4151-80bd-547989a10b46)
If you're asking yes the setting are enabled

**Comment by Johni0702** [comment]
What's the value of your `Singleplayer Server View Distance` in Bobby's settings?
Also, which mods (and their exact versions) are you using?
