### ISSUE TITLE
Can I make Bobby save data from a server into a singleplayer world?

### ISSUE THREAD

**Issue by JAcamp1** [Johni0702/bobby#164]
I have a server that was recently griefed and while I do not have a backup I still when logging in see flashes of bobby data before the server sends chunks.  Using MCAselector I am able to see the world but I cannot access it as the chunks loaded in from Bobby's data file are overwritten as soon as a player enters the region. Has anyone found a fix to this or is there a potential way to do so?

**Comment by Johni0702** [comment]
See https://github.com/Johni0702/bobby/issues/89
