### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LadyHaley** [Johni0702/bobby#165]
I play on max fov, and i have noticed bobby will unload chunks that I can still see on screen in the corners of my high fov

**Comment by LadyHaley** [comment]
![2023-06-06-22-45-59](https://github.com/Johni0702/bobby/assets/3754909/73391788-7ae1-49df-889d-a44bf0d9afa8)
![2023-06-06-22-46-06](https://github.com/Johni0702/bobby/assets/3754909/be75df1c-a289-45ac-9198-3b52b0064904)

**Comment by LadyHaley** [comment]
The speed effect and I presume the fov change with bows would also cause this issue

**Comment by Johni0702** [comment]
Bobby does not care about where you look or what your fov is. It loads all chunks all around you.
It's whatever performance mod you use (or the vanilla game) that decides which chunks to actually draw on the screen. Bobby just provides them all, it has no say in which of them actually get displayed.
Specifically in this case I believe it's nothing to do with fov at all and is merely an artifact of how the game decides which chunks to draw: There needs to be a continuous path of loaded chunks on screen for any chunk to be drawn. And if you look closely, you'll see that the only path to the chunks that disappear is on the very edge of the screen, so once that goes off-screen, the entire section of now-no-longer-connected chunks disappears.
