### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by SecretlyJealous** [Johni0702/bobby#167]
Could you update the mod to 1.20 when you get the chance

**Comment by KevM** [comment]
FYI I really appreciate this mod. Thank you for working hard to maintain it. When you get to 1.20 you get there. We will wait patiently. 💟

**Comment by sternschnaube** [comment]
Looking forward to it, thanks 😊

**Comment by Kadeluxe** [comment]
No

**Comment by Johni0702** [comment]
Released as Bobby 5.0.0 to GitHub, Modrinth and (once approved) CurseForge.

**Comment by sternschnaube** [comment]
Thanks alot!!
