### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by Playz-byte** [Johni0702/bobby#169]
I've been playing on 1.20 rather then updating to 1.20.1 because there is no point in my eyes really. So Bobby was updated for 1.20.1, but not 1.20, why would you skip this? Don't get me wrong, I love bobby, but I would really prefer to not update my client.

**Comment by lazybones678** [comment]
I Fully agree that we need a 1.20, For there are mostly 1.20 servers and very few servers are switched onto 1.20.1 . Meaning ,the better option is add 1.20 because more people/servers are already using it and most smps don't have cross version support.

**Comment by XavierBit** [comment]
First, I love Bobby and I'm grateful for all the work which goes to this mod. Playing on server without it, is just a pain.
But I second the OP wish for an 1.20 version. Many servers are lagging behind because the 1.20 to 1.20.1 changes are minimal.

Please consider :)

**Comment by nipocx** [comment]
> First, I love Bobby and I'm grateful for all the work which goes to this mod. Playing on servers without it, is just a pain. But I second the OP wish for an 1.20 version. Many servers are lagging behind because the 1.20 to 1.20.1 changes are minimal.
> 
> Please consider :)
> 
> Edit: Modifying the fabric.mod.json to "minecraft": "~1.20.0" will work, but I can't get into the options menu. Mod menu will not show an option and there is no keybind in MC. It's ok for a quick fix, but there is some more work needed.

How do I do this? I can't find fabric.mod.json anywhere.. 

I would also really like a 1.20 version :(

**Comment by XavierBit** [comment]
I couldn't access Bobby's options, did you?

**Comment by nipocx** [comment]
> I couldn't access Bobby's options, did you?

Yes, it works like a charm.

**Comment by TimeIgnited** [comment]
I also couldn't access options. It seems like it's installed, but the button to enter the config menu is not present.

**Comment by TimeIgnited** [comment]
YES! I found a file called bobby.conf finally I can configure it... Might be nice to mention this on the page that this has changed how to configure it

**Comment by StasysMusial** [comment]
> I Fully agree that we need a 1.20, For there are mostly 1.20 servers and very few servers are switched onto 1.20.1 . Meaning ,the better option is add 1.20 because more people/servers are already using it and most smps don't have cross version support.

same reason i am here, i run a small smp with about 15 people. were on 1.20 and will only update once the (hopefully) final 1.20.x version releases. if i may ask, what is the point in porting to 1.XX.1 and not to 1.XX.0 while its kinda obvious that most people starting a new world or coming back to the game will most likely do so within a couple days of the update release date no? really dont mean to be rude, but id be very interested

**Comment by Johni0702** [comment]
See https://github.com/Johni0702/bobby/issues/171
