### ISSUE TITLE
we need a 1.20 support its dumb

### ISSUE THREAD

**Issue by MTG2k23** [Johni0702/bobby#171]
does everyone agree? we need a 1.20 support, its a bit dumb that its on 1.20.1 and not 1.20 if anyone agrees please reply to get this solved

Thanks

**Comment by onkoe** [comment]
uhhhh yeah... but no need to be rude to the maintainers! a 1.20.0 release probably wasn't on their mind after they finished testing their changes :p

**Comment by StasysMusial** [comment]
yeah no reason to be rude, but i agree with the demand :) 1.20.0 support would be huge!!

**Comment by Wyne10** [comment]
I added 1.20 support #170

**Comment by Johni0702** [comment]
The reason this is on 1.20.1 is that that's the version I build and tested it against and so I'm not going to claim that it supports 1.20 when I haven't tested that.
More importantly though, 1.20.1 came out literally less than a week after 1.20, is network compatible with 1.20 and the absolute vast majority of mods are compatible with it with no changes. There's really no reason to use 1.20 at this point.
