### ISSUE TITLE
Bobby chunks disappear / appear randomly depending on player position and camera direction

### ISSUE THREAD

**Issue by FernanIGF** [Johni0702/bobby#174]
https://github.com/Johni0702/bobby/assets/71931361/4272f550-e034-44b7-8abc-accf0f44b0df

**Comment by FernanIGF** [comment]
This is on 1.19.2 server

**Comment by Johni0702** [comment]
Bobby doesn't depend on the camera rotation. This is either a bug in Sodium/Iris (assuming you're those) or just a side-effect of how Sodium (and also the vanilla game) render chunks when not all chunks between the camera and the target chunk are available (see #165; though it doesn't quite look like that unless there's chunks missing right below you that one can't see from up here).

**Comment by FernanIGF** [comment]
The chunks below me don't disappear, only the chunks uploaded by bobby disappear, the 10 chunks from the server never fail

**Comment by FernanIGF** [comment]
I have tried to remove bobby and change the server distance to 32 chunks and all the chunks load without problems

**Comment by Johni0702** [comment]
That's entirely consistent with what I said...
