### ISSUE TITLE
This is normal?

### ISSUE THREAD

**Issue by Nukecraft5419** [Johni0702/bobby#181]
We in the LifeMC Studios team have noticed that using Bobby every time this happens we also get an error in the .bobby logs

![lifemc_2023-06-27_17 02 35](https://github.com/Johni0702/bobby/assets/72621737/0fc88da7-08ad-46a2-ae21-fc70cb5503b5)

https://mclo.gs/rHp7KeT

**Comment by Johni0702** [comment]
Certainly doesn't look normal.
Do you have a reliable way to reproduce that? If so, can you still reproduce it with all third-party mods removed? If not, what's the minimal set of mods to reproduce it?
Also, what error are you referring to? I can't find anything mentioning bobby directly and all the hypixel spam makes it impossible to just read through all of it.

**Comment by Johni0702** [comment]
Oh, actually, idk what I'm looking at, but if that's a world from another minigame and you'd expect there to be void there instead (or something else you haven't explored yet), then that is normal: See https://github.com/Johni0702/bobby/issues/72

**Comment by Nukecraft5419** [comment]
On the blank part yes and true I would expect the blank, as for the logs centred on the fact of the .bobby not being emptied just go to the log link and select only the errors and the first one should be

**Comment by Johni0702** [comment]
> as for the logs centred on the fact of the .bobby not being emptied just go to the log link and select only the errors and the first one should be

No?
![](https://i.johni0702.de/mhvLY.png)

I used ctrl+f for my initial search, there's seven mentions of `bobby` and all of them are completely normal.

> On the blank part yes and true I would expect the blank

Then this is just the same issue as the one I linked and I'll close it as a duplicate. If you believe it to not be the same issue, then properly explain what you mean by "this happens".

**Comment by Nukecraft5419** [comment]
Very strange, however basically and this one I copied https://mclo.gs/suJNDHK
