### ISSUE TITLE
The extra chunks are simply not loading

### ISSUE THREAD

**Issue by NTLISHOTANDSOISLINUS** [Johni0702/bobby#184]
I have turned everything on in the mod-menu settings to but I cannot see any extra chunks. Can you help?

**Comment by Johni0702** [comment]
You need to give me something to go off of. Just saying "I installed the mod like everyone else" doesn't give me any information on why it doesn't work for you like it does for everyone else.
For example: Screenshots of your bobby and minecraft render settings, a screenshot showing the chunks you expect to be there, a screenshot from further away showing the chunk missing (with F3 enabled), the `latest.log` file.
