### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by yahoooooooooooooooooooooooooooooooooo** [Johni0702/bobby#188]
I have a friend that tried to use the mod on ios, it works but we couldn't find the bobby folder to change the map (it was for wynncraft) and get the fully loaded map in

**Comment by Johni0702** [comment]
Bobby places its folder in the same place (`.bobby` inside the `.minecraft` or equivalent folder) on any platform. How you find that folder is specific to your Operating System and/or Launcher, and not something I can help with.
