### ISSUE TITLE
Unable to load chunks in Singleplayer

### ISSUE THREAD

**Issue by 0808dion** [Johni0702/bobby#189]
Bobby has been working great on multiplayer, but I can't get it to work on singleplayer.

I have set Singleplayer Server View Distance to 32, but nothing is rendering beyond my render distance of 16. However, when I fly towards the edge of my render distance with Freecam (which doesn't load chunks that aren't within range of my player), chunks up to the expected 32 load in. They do unload once I deactivate Freecam, though.

![2023-07-10_09 35 02](https://github.com/Johni0702/bobby/assets/139109761/d24c72b9-1bd7-4d66-9157-5e1abd019a31)
This is my normal render distance. I'm currently removing distance fog with Sodium Extra while I'm experimenting since Bobby isn't increasing the distance on it, but I'm assuming that's an issue that'll fix itself once Bobby's chunks start loading properly.

![2023-07-10_09 35 24](https://github.com/Johni0702/bobby/assets/139109761/774d53a1-c204-4ed8-b663-7e9886c7b007)
This is what happens when I fly past my render distance with Freecam. It loads chunks beyond it, but only up to 32 chunks away from my player's position. This is Bobby loading in chunks because when I disable the mod and relog, they don't appear.

I'm normally using the following mods:
- Architectury-9.0.8-fabric
- BetterF33-7.0.0-Fabric-1.20-pre6
- Bobby-5.0.0
- Camerautils-1.20.1-1.0.4
- Cloth-config-11.0.99-fabric
- Fabric-api-0.83.1+1.20.1
- Freecam-fabric-1.2.0+1.20
- Gamma-Utils-1.7.14-mc1.20
- InventorySorter-1.8.10-1.20
- Iris-mc1.20-1.6.4
- Journeymap-1.20-5.9.8-fabric
- Light-overlay-8.0.0
- Litematica-fabric-1.20.1-0.15.0
- Lithium-fabric-mc1.20.1-0.11.2
- Logical_zoom-0.0.20
- Malilib-fabric-1.20.1-0.16.0
- Minihud-fabric-1.20.1-0.27.0
- Modmenu-7.1.0
- MouseTweaks-fabric-mc1.20-2.25
- Reeses_sodium_options-1.5.1+mc1.20-build.74
- Shulkerboxtooltip-fabric-4.0.3+1.20
- Sodium-extra-0.4.20+mc1.20-build.103
- Sodium-fabric-mc1.20-0.4.10+build.27
- Soundphysics-fabric-1.20.1-1.1.1
- Worldedit-mod-7.2.15

I also tested with the bare minimum mods:
- Bobby-5.0.0
- Fabric-api-0.83.1+1.20.1
- Freecam-fabric-1.2.0+1.20
- Modmenu-7.1.0
- NoFog-1.3.4_1.16.5-1.20.1-fabric

With these mods it just acts like it's completely vanilla. It doesn't load in chunks beyond my render distance when I get close with Freecam.

I hope this is enough information

**Comment by Johni0702** [comment]
> I have set Singleplayer Server View Distance to 32, but nothing is rendering beyond my render distance of 16

You've got them flipped. Singleplayer Server View Distance is the distance the server loads; render distance is how many chunks it'll actually display on screen (it rendering more while freecaming is likely a side effect of how the freecam interacts with sodium). The latter must be larger than the former for bobby to have any effect. In your case, the integrated server is already sending you chunks within 32 distance but you're only drawing those within 16 distance.
