### ISSUE TITLE
Light not being updated when breaking and placing blocks

### ISSUE THREAD

**Issue by xpopy** [Johni0702/bobby#19]
![2021-03-23_15 43 09](https://user-images.githubusercontent.com/3540971/112166174-b11f5f80-8bef-11eb-96e3-2393b02a9d3d.png)

It only seems to happen when there's a lot of chunks loaded (like 32 chunk render distance)
Even when placing a torch nearby it doesn't update the light
This is without any light modifying mods, but in case it would help these are the mods i'm using:

Architectury
Autorun
Betterbeds
Blockmeter
Blur
Bobby
Cloth-config
Cmdkeybind
Connected-block-textures
Dynamic-fps
Fabric-api-0.31.0
Fallingleaves
Hydrogen
Indium
Krypton
LazyDFU
Lithium
Logical zoom
Mod menu
Soaring Clouds
Sodium extra
Sodium 0.1.1 (latest build)
Tic-tacs

**Comment by Johni0702** [comment]
Could you please try without any other mods and if that works try to narrow it down to which mod is breaking it?

**Comment by xpopy** [comment]
Did some testing, I managed to replicate it using only sodium 0.1.1 snapshot, fabrics api 0.31.0 and bobby 1.1.1

Everything looks fine when I connect to the world, but after going through a nether portal to somewhere far away and then coming back, thats when the light bug appears

**Comment by xpopy** [comment]
After some futher testing I can't seem to replicate this on my own server (1ms ping) but I managed to do it on two other servers (100ms+ ping). Idk if the ping or server performance has anything to do with it

**Comment by Johni0702** [comment]
Thanks for your testing! After some concentrated starring at the Sodium-specific code I was able to find a potential race condition which indeed would be influenced in part by network bandwidth (specifically it only behaves badly if the time between the respawn packet and the chunk packets is longer than it takes MC to render a frame; rarely the case on a local server / singleplayer where I usually test).
And indeed with a bit of careful time manipulation in the right places I am able to reliably reproduce your issue. I'll publish a 1.1.2 version with the fix shortly.
