### ISSUE TITLE
Shadows on the ground 

### ISSUE THREAD

**Issue by XavierBit** [Johni0702/bobby#193]
Hi!
I'm using Minecraft 1.20.1 with Sodium 0.4.10 build 27 and an AMD Ryzen 7 2700x as well a NVIDIA GeForce RTX 2070. There are minimum 4GB and max 6GB RAM allocated and this example is on a single player world. Bobby settings are as they come.

On a new instance, creating a new super flat world, there are visual shadows, where nothing it covering the ground.
![2023-07-11_19 42 09](https://github.com/Johni0702/bobby/assets/95314871/de282ec6-979f-4d8f-8051-5a9ed17f46d4)

The F3 screen tells me, that the light level is 15.

When updating the chunk with any block or a light source, it seems to change the bounding chunks:
![2023-07-11_19 43 50](https://github.com/Johni0702/bobby/assets/95314871/42bfb646-3da3-4c00-b951-b4921b82c8b1)

Logging out and back in:
![2023-07-11_19 45 37](https://github.com/Johni0702/bobby/assets/95314871/a3295e2d-a1fe-428e-a494-b07e9a5f39f4)

This problem does occur in normal world generation as well but it seems less often:
![2023-07-11_20 14 06](https://github.com/Johni0702/bobby/assets/95314871/448e63ed-ea01-43ab-863f-a6c2a3118aed)

Any Idea how I can prevent this problem?

**Comment by MasonIsEpic** [comment]
Use F3 + T to reload your texture packs. It should fix any visual and or audio glitches.

**Comment by XavierBit** [comment]
Yes, F3+T helps temporarily, going to the Nether and coming back or just logging out and back in will create the same black spots.
I narrowed down the mod which causes the problem. Seems a setting in 'Sodium Extra' causes it. If I run the game with Fabric API, Sodium, Sodium Extra and Bobby I get the effect. If I disable Sodium Extra, I don't.

Here are the Sodium Extra setting: https://pastebin.com/CXp8Qv4r

Any suggestions what's wrong with it?

**Comment by XavierBit** [comment]
Good to know I`m not alone with this problem:

- Mumbo showed those dark spots in his video https://youtu.be/aBBSxzFO5A8?t=331
- Docm77 mentions them as well https://youtu.be/Ze0nHFkFXYI?t=155

Both are using Bobby!

**Comment by Meister182** [comment]
Same here.. I'm confused, Is it a sodium issue? Ive tried with and without bobby and can only reproduce it with bobby..
Anyway, placing or removing a block on those "dark chunks" seems to update them, and they go back to normal.

**Comment by OldMensch** [comment]
Yeah currently using bobby-5.0.3 on 1.20.4 here... same issue, in singleplayer specifically. I'm able to reproduce the "dark chunks" issue wherever I go, most obviously when flying around at high speeds in spectator mode. Seems that chunks right on the edge of the "singleplayer server view distance" start out completely black after converting from fake to real chunks. I don't seem to have the issue when heading in the direction of chunks that aren't in bobby's cache, only cached chunks.
You can see it very clearly right along the 32-chunk border, in this case. If you reduce the "singleplayer server view distance" setting the blacked chunks appear closer to the player instead.
![2024-01-27_01 57 05](https://github.com/Johni0702/bobby/assets/88910933/9a34a11c-5af8-4431-b318-8ede7cc18d09)
Most of the time, the lighting issue corrects itself either immediately, or when getting closer to the chunk, but occasionally it lingers until you modify the chunk.

**Comment by Johni0702** [comment]
Not an issue with Bobby.
Bobby isn't enabled in Singleplayer by default and the F3 screenshot seems to confirm that it was not active at the time.

If you are experiencing a similar problem and have Bobby enabled, make sure it is not caused by another mod you also have installed, and then please open a separate issue.
