### ISSUE TITLE
Crash on start - 1.19.4 & 1.20.1

### ISSUE THREAD

**Issue by WreckedAP** [Johni0702/bobby#196]
Hello,

I recently updated from 1.19.4 to 1.20.1 due to an issue where attempting to load Bobby crashes upon launching. This issue is still happening in my 1.20.1 version.

I have tried different versions of Bobby & its dependencies to no avail.

[crash-2023-07-27_21.35.11-client.txt](https://github.com/Johni0702/bobby/files/12189275/crash-2023-07-27_21.35.11-client.txt)

Any help would be appreciated.
Thanks,
Wrecked

**Comment by UnknownNate** [comment]
Having the exact same error (1.19.4). I've tried both updating and downgrading fabric and bobby but neither have worked. Issue only showed up after I updated all mods through curseforge

**Comment by Johni0702** [comment]
Please attach the full log file. There should be an error that happened before the crash.

**Comment by UnknownNate** [comment]
[latest.log](https://github.com/Johni0702/bobby/files/12330270/latest.log)

**Comment by Johni0702** [comment]
Looks like a few of your config files have become corrupted. Try deleting `.minecraft/config/bobby.conf`.
"visuality" and "fpsreducer" are emitting config file related errors as well, so you may have to delete their config files as well.

**Comment by UnknownNate** [comment]
Deleting config worked, ty!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Johni0702/bobby/issues/196#issuecomment-1676489801

@UnknownNate, this may have worked for @JaredRichardWilliam and I too - during diagnosis of https://github.com/TheCSMods/mc-better-stats/issues/142#issue-2599605595, constant game crashes on multiplayer join affected us, until we reinstalled our mod-pack.
