### ISSUE TITLE
Add ingame option to disable the mod

### ISSUE THREAD

**Issue by Johni0702** [Johni0702/bobby#2]

**Comment by RYRY1002** [comment]
Just go into mod options on Forge and disable the mod from there.

**Comment by Johni0702** [comment]
> Just go into mod options on Forge and disable the mod from there.

This is neither a Forge mod nor would the disable button actually do anything until implemented by the mod author.

**Comment by RYRY1002** [comment]
Oh yeah, I forgot it was Fabric.
