### ISSUE TITLE
Real chunks are not being loaded

### ISSUE THREAD

**Issue by xpopy** [Johni0702/bobby#20]
Seems we're not done just yet, 1.1.2 broke loading the real chunks
Probably related to the fix of #19 but I feel like it's a separate issue
![unknown](https://user-images.githubusercontent.com/3540971/112324237-db862100-8cb2-11eb-845f-f59a3e8f3980.png)

**Comment by xpopy** [comment]
Forgot to mention this happens only on servers, including my own server with low ping
And the mods used are: Sodium snapshot, fabrics api and bobby

**Comment by Johni0702** [comment]
Oh, my bad, should have really tested it before publishing.
