### ISSUE TITLE
Crashes everytime i join a server

### ISSUE THREAD

**Issue by Akiakoss** [Johni0702/bobby#200]
I installed the mod and i wanted to try it out I joined my server and the game crashes.
(without the mod enabled in the config)

**Comment by Columbam1998** [comment]
Latest version is not compatible with the latest version of sodium. (they're working on it)

**Comment by Akiakoss** [comment]
I didn't use the latest sodium version.

**Comment by Johni0702** [comment]
Then please attach the crash report and full log file from `.minecraft/logs/latest.log` after trying to start the game.

**Comment by Akiakoss** [comment]
it works for some reason
