### ISSUE TITLE
Using /bobby upgrade doesnt make good use of hardware

### ISSUE THREAD

**Issue by EmmaKnijn** [Johni0702/bobby#207]
Using /bobby upgrade can be very slow, even if you have a good CPU
![image](https://github.com/Johni0702/bobby/assets/64010592/faeecda3-fede-4aaa-be54-2ee03db58040)
A potential fix would be to multithread the chunk upgrading process by splitting the world in the same amount of parts that you have threads

**Comment by Johni0702** [comment]
The actual upgrade process is already multithreaded. Minecraft's reading/decompression and writing/compression code however is limited to a single thread, and I suspect that's the bottleneck in your case. Not much I can do about that without re-implementing all of that, and that's too out of scope imo given it'd only really help for this one, relatively infrequent, procedure.
