### ISSUE TITLE
SOLVED - Bobby isn't compatible with Sodium 0.4.10+build.27... or is it just me?

### ISSUE THREAD

**Issue by XavierBit** [Johni0702/bobby#209]
Hi!
I receive:
![image](https://github.com/Johni0702/bobby/assets/95314871/e3777567-857e-4e03-b999-d46f7b76a48c)
When starting the game.

Is it just me or is this a known bug?

Sorry, my bad. my Sodium version wasn't up to date!

**Comment by Johni0702** [comment]
Bobby prior to version 5.0.1 is only compatible with Sodium 0.4.x.
Bobby as of version 5.0.1 is only compatible with Sodium 0.5.x.
