### ISSUE TITLE
I can's seem to make bobby work on my world, i set 128 chunks but it stays on 32, i'm on 1.20.1 and everything is up to date. These are my mods.

### ISSUE THREAD

**Issue by Rizitoss** [Johni0702/bobby#212]
![Mods 1 20 1](https://github.com/Johni0702/bobby/assets/117871913/cbbb4aa4-57b7-4e5f-88d6-34068ea116f7)

**Comment by Rizitoss** [comment]
Also this appears when i type bobby upgrade 
![image](https://github.com/Johni0702/bobby/assets/117871913/e006ece9-6063-4071-b104-5378d9481777)

**Comment by Rizitoss** [comment]
This are my settings 
![image](https://github.com/Johni0702/bobby/assets/117871913/f3e86d74-e5d3-4fd2-874a-3a6f256b5b64)
![image](https://github.com/Johni0702/bobby/assets/117871913/2099a926-895d-4ea8-b69a-53c81c4fb00e)

**Comment by Rizitoss** [comment]
I'm on single player aswell

**Comment by etturbo** [comment]
I'm playing on a server and have the same problem...

**Comment by Josh65-2201** [comment]
You need to have Singleplayer server view distance at a value other then 0 for it to work in Singleplayer

**Comment by berat615141** [comment]
I just want set the distance to the 64 chunk i tried singelplayer server distance at 64 and the normal render distance at 64 but its not loading new chunks. When i use render distance at the 64 chunk its just shows the old chunk i loaded and the new ones loading at 32 chunk. Using singelplayer server distance other then 0 is nonsense why someone need to use bobby in the singelplayer there is no limitations the ones server has and i dont want to give storage for singelplayer world. Why does the setting 64 to render distance isnt working.
