### ISSUE TITLE
I dont get any effects from eating golden apples or drinking potions while using bobby

### ISSUE THREAD

**Issue by xBlur25** [Johni0702/bobby#213]
I tried to disable any mod one by one and its the bobby mod that causes it

**Comment by Johni0702** [comment]
Any steps for how to reproduce this?

**Comment by xBlur25** [comment]
I dont know, i could send you every mod i am using but i checked and it
turned out that it only worked once i turned your mod off

Am Sa., 9. Sept. 2023 um 18:21 Uhr schrieb Jonas Herzig <
***@***.***>:
