### ISSUE TITLE
Bug: Chunks are not being saved/loaded correctly

### ISSUE THREAD

**Issue by Josh65-2201** [Johni0702/bobby#214]
## Description
I have only tried on a server and the files are being save to the .bobby folder they do not load in-game. This also happened when too many chunks are loaded in a session or switching worlds.

## Steps to reproduce 
1. Load a server
2. Set local view distance to a higher value then server
3. Load chunk outside of server view distance
4. Rejoin Server
5. See chunk are not loaded until I got there

## Logs
None

## Versions
Minecraft: 1.20.1
Bobby: 5.0.1
Sodium: 0.5.2

**Comment by FellowRabbit** [comment]
I'm not sure if I'm having exactly the same issue as you, but it sounds similar I think? The mod just doesn't work now and I've tried everything, including removing all my other mods to see if something is randomly conflicting. I can toggle Bobby and at most I see 2 more chunks than normal where I used to be able to see the full 64 I had it set to. Tested on a singleplayer world as well and still doesn't work. I had it working great for a couple weeks after first intalling it and now it's just dead

**Comment by Johni0702** [comment]
> Logs
>
> None

Please attach the `latest.log` after reproducing the issue. I suspect there may be further information in there.
Please also take a screenshot of the F3 screen a few seconds after finishing your reproduction steps.

> This also happened when too many chunks are loaded in a session or switching worlds.

What do you mean "also"? What happens?

**Comment by Josh65-2201** [comment]
Not sure why it seem to be working again even after multiple relaunches.

**Comment by Whunot** [comment]
Well, now i have absolutely the same issue.
I load chunks on the server, but after each reboot I have to render them again
[latest.log](https://github.com/Johni0702/bobby/files/12623992/latest.log)
