### ISSUE TITLE
Bobby's singleplayer mode doesn't work on sodium 0.5.2 Quilt

### ISSUE THREAD

**Issue by k0nstruct** [Johni0702/bobby#215]
Title says it all : Having my bobby (single player!) render distance set to 32, I still have 12 chunks render distance. (arbitrary value)
No other mods installed except sodium extra (to remove fog), Reese's sodium options and modmenu.
I'm using Quilt loader 0.20.2 on multiMC for Minecraft 1.20.1.

If you need any info ask me, I'll happily give what I know

**Comment by Johni0702** [comment]
There is no "bobby render distance". Did you maybe mix up the two distances like https://github.com/Johni0702/bobby/issues/189#issuecomment-1676307292?
