### ISSUE TITLE
Local Chunk Generation for Unvisited Areas

### ISSUE THREAD

**Issue by SnowSquire** [Johni0702/bobby#218]
It would be nice if bobby could generate chunks using the seed of a server if its known, this way you can always have a consistent render distance.

**Comment by tunaflsh** [comment]
This can introduce a lot of glitches and conflicts. How do you know those areas weren't loaded on the server and modified by someone?

**Comment by SnowSquire** [comment]
How do you know any of the cached chunks weren’t modified by someone else? The whole mod is about making assumptions to give a fake increased render distance

**Comment by Hokage3211** [comment]
I think it does do this, if you have a local singleplayer world called "bobby fallback" like the mod description says, but the current problem is that as far as I can tell, it's a global fallback, so every server will show those for un-seen chunks (even if it's a totally different server)

**Comment by SnowSquire** [comment]
It doesn't generate chunnks, just uses the already generated chunks of the world. Which makes it kinda useless in my opinion

**Comment by Its-Just-Luci** [comment]
I was honestly wondering if this was a glitch on my end... Am I really meant to only be able to see 3-4 chunks when I load in a world before I move?

**Comment by tunaflsh** [comment]
@Its-Just-Luci the mod doesn't generate chunks. It only caches them locally, so it loads already explored chunks before the server sends them to you. But if you have a seed of the world, you could play around with "bobby fallback" that was mentioned in the mod description.

**Comment by Johni0702** [comment]
Going to close this because local background chunk generation is a lot more tricky than one would expect, so it's unlikely to ever happen.
