### ISSUE TITLE
Sodium compatibility issue

### ISSUE THREAD

**Issue by DarkAndBlue** [Johni0702/bobby#22]
When using Bobby 1.1.4 with a self build version of Sodium I get this error from Sodium (Newest version from the default branch)

https://ghostbin.co/paste/66vm7mj

I also have a older version of Sodium and with this version I dont get this error. 
When join a server while this error occurs Bobby doesn't load any more chunks than the normal server distance.
When I remove Bobby and start my own build Sodium version I don't get the error anymore.

**Comment by Johni0702** [comment]
Only the latest Sodium release is supported. Just like only the latest Minecraft release is supported. I simply don't have the time to keep it updated with every Sodium snapshot (just like I don't have the time to keep up with every Minecraft snapshot).

Feel free to remind me again when the new Sodium version is released.

**Comment by NebelNidas** [comment]
But it shouldn't be hard to fix, because Sodium now uses the vanilla Minecraft chunk manager (instead of the old re-implementation): https://github.com/CaffeineMC/sodium-fabric/commit/6caf15fcb84dcaa26175fe88d29cd9cd0e3ab6f3

**Comment by Johni0702** [comment]
It's probably not hard to fix at all but as I said:
> I simply don't have the time to keep it updated with every Sodium snapshot (just like I don't have the time to keep up with every Minecraft snapshot).

**Comment by NebelNidas** [comment]
@Johni0702 I got confirmation from the Caffeine team that there will indeed be a final 1.16 release with all of the current changes: 
![image](https://user-images.githubusercontent.com/48808497/120897810-4eebcd80-c628-11eb-8331-b301a43671b4.png)

So I guess you have to fix it now either way 😉

**Comment by Johni0702** [comment]
> Feel free to remind me again when the new Sodium version **is released**.

**Comment by Johni0702** [comment]
FYI Bobby 1.2.0 should be compatible with Sodium 0.2.0 (or at least with 0.2.0-rc4).
Ended up doing this before the actual release because I wanted to get to Minecraft 1.17 (Bobby 2.0.0), and there's a chance that the Sodium 0.2.0 specific code continues working in MC 1.17 once Sodium for that version is available if it doesn't change too much.

**Comment by NebelNidas** [comment]
Thank you very much! 🥳 Sorry for annoying you previously, I just wanted to use Iris asap without having to give up my 32 chunks view distance on my server 😉
