### ISSUE TITLE
Bobby chunks keep needing to upgrade when joining server

### ISSUE THREAD

**Issue by Saraldar** [Johni0702/bobby#223]
One day I decided to upgrade my mod list from 1.19.4 to 1.20.2 but after testing it out it gave my a lot more performance related issues.
So I switched back, but ever since I did when joining the server I usually play on (wynncraft) the mod says to upgrade my chunks.
It does not seem to matter how many times I do it, it keeps not remembering the upgrading process after restarting mc.

Having the option to either have bobby not being able to pull any cached chunks or sitting at my desk while it upgrades over 2 million chunks every time I want to play isn't great.
I have not found a case with similar issues.

Thanks for the time.

**Comment by Johni0702** [comment]
Minecraft doesn't support downgrading chunks.
If you don't have a backup of the original 1.19.4 cache, you'll need to delete the `.minecraft/.bobby/play.wynncraft.com` cache.
