### ISSUE TITLE
Bobby cant configure

### ISSUE THREAD

**Issue by Mrgigadoge** [Johni0702/bobby#227]
im unable to configure the mod so i can like have the render distance changed
![image](https://github.com/Johni0702/bobby/assets/155001624/4866a442-9860-45f1-9936-b3bbe886b45f)

**Comment by Invoren** [comment]
I am also having the same issue did you fix it?

**Comment by JohnDildoe** [comment]
i also have this issue too,
but don't know how to fix it.

**Comment by Johni0702** [comment]
As it says in the README file, to get the ingame config screen you need to install ClothConfig.
Be sure to get the Fabric version, not the Forge one.
