### ISSUE TITLE
Async ViewDistance - Sentence

### ISSUE THREAD

**Issue by ghost** [Johni0702/bobby#23]
Hi, I have a cool idea!
Your plugin generates chunks, but if you can implement visibility like this plugin, it will be a breakthrough!

https://www.spigotmc.org/resources/fartherviewdistance.84950/

I would really like to see a similar implementation for 1.17 for my future Fabric server.

**Comment by Johni0702** [comment]
This is not a plugin, it is a client-side mod which works on any server. It does not generate chunks, only keep track of ones which it has already seen.

I don't understand what specific feature you're looking for.
