### ISSUE TITLE
Increasing Render Distance to 64 using Sodium does not work

### ISSUE THREAD

**Issue by Uniter343** [Johni0702/bobby#230]
## Description 
Using Bobby and Sodium to overwrite the 32 chunk Render Distance limit does not seem to work.

## To Reproduce

1. Set Bobby's max render distance and view distance overwrite to 64 
2. (`max-render-distance=64` and `view-distance-overwrite=64` in bobby.conf)
3. Set the Render Distance to 64 in the video settings
4. (`renderDistance:64` in options.txt)
5. Launch/Restart the game
6. Create a new world, don't move and let the chunks finish loading
7. Open the debug screen (F3) and verify the Render Distance is set to 64 (4th row behind the D)
8. However you will see that the Amount of Loaded Chunks is 3653, the same number that is loaded at 32 Render Distance
9. It can also be visually confirmed that the Distance that is rendered is the same at 32 and 64 chunks Render Distance (Border Fog/Fog Occlusion does not work at 64 Render Distance)

## Expected behavior
The Render Distance that is visible is actually 64 chunks

## Versions
fabric-loader-0.15.3-1.20.2
fabric-api-0.91.2+1.20.2
bobby-5.0.2
sodium-fabric-mc1.20.2-0.5.5

## Java & Drivers
Java 17.0.8 64bit
GPU Driver: 3.2.0 NVIDIA 537.58

**Comment by Johni0702** [comment]
The integrated server is limited to 32 chunks view distance, so `view-distance-overwrite` must not be set to a value larger than that.
You need to move around to get it to generate more chunks. Once you've moved around and visited those chunks, Bobby will have them cached and whenever you re-enter the world it should load them.
