### ISSUE TITLE
[question] How do we know when to use bobby-fallback for a singleplayer world

### ISSUE THREAD

**Issue by woobeewoop** [Johni0702/bobby#232]
Hello! Ive been messing around with this mod for a while, and it is great! For a single player world, I know you can change the folder to bobby-fallback to load chunks the server has not sent before. I was wondering in what cases this should be used. For made a new survival world and have the view distance at 64 with the "single player server view distance" at 32. With these settings, would it be advantageous to rename the world folder to "bobby-fallback" / how does one gauge that in general?

**Comment by Johni0702** [comment]
The main (and really, only) use case of the `bobby-fallback` mechanism is for when you have a larger existing world which you want to feed into bobby so you don't have to run around once to cache everything.
If you're creating a new world, any chunks you generate will already be cached by Bobby as you first explore them, so there's no advantage to using the `bobby-fallback` mechanism.
