### ISSUE TITLE
Singleplayer world not rendering more than 32 Chunks

### ISSUE THREAD

**Issue by Grizzly096** [Johni0702/bobby#235]
I am in a Singleplayer world and I have set 
max-render-distance=1000 
view-distance-overwrite=1000

even though those distances are a bit overdramatic ive done them for testing. Now in Singleplayer worlds there are around 82K Chunks loaded when I dont move (Which is 64 Chunks diagonally). But If I set my render distance to 128 it doesnt show any more Chunks.

Even though ive looked at several other posts with the same problem, nothing has helped me

If there is any other screenshots I could help with then please say so
![2024-01-13_21 06 44](https://github.com/Johni0702/bobby/assets/106621431/64d0c061-9ad1-4794-86f7-bb2c65c510de)
![2024-01-13_21 06 03](https://github.com/Johni0702/bobby/assets/106621431/a057d91e-b2fe-4a86-8793-91f513e9f443)
![2024-01-13_21 06 09](https://github.com/Johni0702/bobby/assets/106621431/33e9565a-42b4-4001-9772-a9aa76aed22d)

```
# Delete regions from the cache when they have not been loaded for X days.
# 
# The cache for a given world is cleaned up whenever you disconnect from the server.
# Entire worlds are cleaned up when the game starts and you have not visited them for X days.
# 
# Set to -1 to disabled.
# Set to 0 to clean up everything after every disconnect.
delete-unused-regions-after-days=-1
enabled=true
# Changes the maximum value configurable for Render Distance.
# 
# Requires Sodium.
max-render-distance=1000
# Do not load block entities (e.g. chests) in fake chunks.
# These need updating every tick which can add up.
# 
# Enabled by default because the render distance for block entities is usually smaller than the server-view distance anyway.
no-block-entities=true
# Reduces the light levels in fake chunks so you can tell the difference from real ones.
taint-fake-chunks=false
# Delays the unloading of chunks which are outside your view distance.
# Saves you from having to reload all chunks when leaving the area for a short moment (e.g. cut scenes).
# Does not work across dimensions.
unload-delay-secs=60
# Overwrites the view-distance of the integrated server.
# This allows Bobby to be useful in Singleplayer.
# 
# Disabled when at 0.
# Bobby is active in singleplayer only if this is enabled.
# Requires re-log to en-/disable.
view-distance-overwrite=1000
```

**Comment by sleitonhar** [comment]
same problem here, but i don't know any solutions sadly...

**Comment by Quvist** [comment]
Might be a clue but I suppose .minecraft/bobby/ is not created? wasnt for me.

**Comment by Quvist** [comment]
Strangely enough I can render clouds from further away but not land or blocks itself.

**Comment by Quvist** [comment]
Seems like I need to be within 32 chunks to render, then when I have it rendered I can see it from further away when I go back. Disabled mod and enabled it and .bobby was created.

**Comment by Grizzly096** [comment]
The thing that you say with chunks staying rendered is due to nvidium I think. But the .minecraft/.bobby folder is created

**Comment by WeeKee77** [comment]
same issue here. What GPU do you have? Does not work on my rtx 4090

**Comment by Grizzly096** [comment]
I have a rtx 2060

**Comment by Johni0702** [comment]
You must not set `view-distance-overwrite` to values greater than 32. There's a reason the slider only goes that far. The integrated server does not support view distances greater than 32.

Please also try without nvidium. Bobby has explicit support for Sodium, but nvidium might break that. According to your F3 screen, Bobby has indeed already loaded 902 chunks (the `F:` number in the 7th line on the left), so it might just be that nvidium simply doesn't display.

Bobby does not in general care about which CPU you use. It only stores/loads chunks to/from disk. The actual displaying of the chunks is left to the regular game code (or Sodium / Nvidium / whatever other renderer you use).

> Might be a clue but I suppose .minecraft/bobby/ is not created? wasnt for me.

Then Bobby is not enabled for you.
If you're in Singleplayer, Bobby is disabled by default, you need to set `view-distance-overwrite` for it to function. See also the docs attached to that setting as well as https://github.com/Johni0702/bobby/issues/110#issuecomment-1294621215 for a longer explanation of what it does.
