### ISSUE TITLE
[Feature request] Add an option to disable the mod on specific servers

### ISSUE THREAD

**Issue by gargondoid** [Johni0702/bobby#236]
On servers such as Hypixel with multiple worlds, the mod saves chunks from one area and puts them into another. For example, when I travel from the lobby to my Skyblock island, some chunks from the lobby remain around my island as they haven't been replaced by new ones from the server yet.

**Comment by Johni0702** [comment]
For the issue with servers that have multiple worlds with identical ids: https://github.com/Johni0702/bobby/issues/72
For the general feature of disabling the mod on specific servers: https://github.com/Johni0702/bobby/issues/128
