### ISSUE TITLE
Nearby subchunks unload as memory fills up

### ISSUE THREAD

**Issue by Egietje** [Johni0702/bobby#237]
When memory has nearly filled up, it seems chunks are culled to ensure it doesn't fill up (?). This seems to affect nearby chunks first, causing the subchunks I'm in/around to get unloaded.
Updating a single block within a subchunk causes it to be rendered again, as does F3+R/F3+T. However, this is tedious and happens nearly every single time memory fills up.
I am using Quilt + Sodium + Nvidium + Bobby.

Before:
![2024-01-17_17 41 25](https://github.com/Johni0702/bobby/assets/20380528/fca3ee02-0b0c-4f7d-94b8-00ad062e3572)

After:
![2024-01-17_17 41 27](https://github.com/Johni0702/bobby/assets/20380528/84e740d8-b3d7-43d9-baf6-ed07b0f4bc6b)

Note the terrain memory usage and memory limit on the right.

ETA:
There is nothing in the logs about this.

**Comment by Johni0702** [comment]
That's either an Nvidium thing, or a thing your graphics driver does.
That line is not present with just Sodium, so I'm assuming Nvidium adds it, and it's GPU memory managed by Nvidium (or the graphics driver on behalf of Nvidium).

Bobby only uses regular memory (the second line on the right) which is no where near full (and there's also no mechanism for unloading chunks when it gets full).
I'd recommend you open an issue on Nvidium's issue tracker, I strongly suspect the same issue would happen without Bobby if there was another way to load lots of chunks.
