### ISSUE TITLE
block updating

### ISSUE THREAD

**Issue by 8n76** [Johni0702/bobby#239]
with the mod enabled, blocks a lot of times dont like to update visually. i can break a block and a lot of times the texture will stay there for longer than 10 seconds. i know this is bobby causing this issue as it doesnt happen when i disable bobby.

**Comment by Fysellynator** [comment]
I'm having the same issue. Disabling bobby, even if only in-game, completely removes this problem.

**Comment by Johni0702** [comment]
I'll need more details. It obviously doesn't happen for everyone, so we'll need to figure out what's different for you, and how I can reproduce it on my machine.

For starters:
What version are you even using?
Do you have other mods installed?
If so, which ones and which versions?
Does it still happen if you remove **all** of them.
Are you in Singleplayer?
Does it happen all the time or only while distance chunks are still loading?
Can you find some way to reliably reproduce it?

**Comment by Fysellynator** [comment]
For me at least, the issue seemed to be caused by the mod Nvidium. I'm on version 1.20.1, and it happens on multiplayer and singleplayer consistently. When I removed Nvidium, the issue stopped, but on a profile with ONLY Nvidium and Bobby the issue also is not present.

**Comment by Rektroth** [comment]
@Johni0702 This issue occurs with Nvidium installed alongside Bobby and "Enable async bfs" turned on in the Nvidium settings. Disabling this feature resolves the issue, but at a _huge_ cost to FPS.

**Comment by Johni0702** [comment]
Nvidium is not something I currently officially support. For any issues with it, please contact its author.
