### ISSUE TITLE
Water not rendering

### ISSUE THREAD

**Issue by aprilkenopsia** [Johni0702/bobby#24]
water on bobby chunks doesnt seem to render (i use optifine so that might be the problem)
it looks normal when i come closer, and it still has a blue look to it so it might just be the way water is rendered (no idea) 

![image](https://user-images.githubusercontent.com/28115928/121234499-25ba7f80-c86a-11eb-80ea-dc726ae0f72b.png)

**Comment by aprilkenopsia** [comment]
also here is a screenshot of my map for comparison
![image](https://user-images.githubusercontent.com/28115928/121234869-91045180-c86a-11eb-848b-8ff38daa81c5.png)

**Comment by Johni0702** [comment]
I'd agree that this looks like something which might be Optifine's fault (ftr I do not support Optifine, if it is at fault, I suggest you look into [alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754)). Could you try without it?
Also, which version of bobby are you using?
To me it looks like what you're seeing is the bobby chunks somehow not having the correct sky light value, i.e. being lit as if there was no water above it. So when testing be sure to re-visit those chunks cause the issue could be with saving as well.
