### ISSUE TITLE
5.1.0 fo 1.20.1 pls

### ISSUE THREAD

**Issue by Spilya** [Johni0702/bobby#242]
I would really like to see the 5.1.0 version of the mod for 1.20.1, since the version in 5.1.0 fixed bug #192.

**Comment by Achim2393** [comment]
Agree with this. have had this issue for quite awhile now, and without the bug fix mentioned it becomes quite unbearable to explore caves when it occurs, without a consistent way to fix it. I am aware that it might take a lot of work on your side, but It would be much appreciated and not go unnoticed.

**Comment by Johni0702** [comment]
[I will generally not be spending time backporting things](https://github.com/Johni0702/bobby/issues/149#issuecomment-1483854615).
If you want the latest features and bug fixes, use the latest version.

**Comment by IMB11** [comment]
@Johni0702 I would appreciate if you could backport 5.1.0 to 1.20.1, as there is no point fixing an incompatability if you're not going to publish the fix for the correct version. See #192
