### ISSUE TITLE
Cannot turn my render distance up past 32

### ISSUE THREAD

**Issue by SelloSqueez** [Johni0702/bobby#243]
The mod doesn't give me the option to turn render distance up past 32. Not sure if graphics card is relevant, but if it is, mine is an RTX 4090, and I use nvidium and sodium.

**Comment by Obscure2020** [comment]
Did you set the render distance maximum to a higher number than 32 in Bobby's config menu _**AND**_ then turn the render distance up in Video Settings? You have to do both, in that order.

**Comment by Mulakulu** [comment]
Yeah, same here. The slider is locked to 32

**Comment by Obscure2020** [comment]
Did you remember to change the maximum in the Bobby config menu first?

![2024-02-20_07 10 03](https://github.com/Johni0702/bobby/assets/69320464/c62b9e99-d3ed-4c44-bcc8-030a9cd5c9f8)

**Comment by Mulakulu** [comment]
There is no config button available for me in the mod menu for some reason. I found the config file in .minecraft/config and did it manually to fix it and it worked.

**Comment by Mulakulu** [comment]
The right version, yes. I installed neoforge by accident
