### ISSUE TITLE
Bobby dousnt load more than 32 chuncks

### ISSUE THREAD

**Issue by oHartog** [Johni0702/bobby#245]
Bobby won't load more than 32 chunks with the most recent version. If I set it to 128 for example it will only show 32.

**Comment by Obscure2020** [comment]
Did you set the render distance maximum to a higher number than 32 in Bobby's config menu _**AND**_ then turn the render distance up in Video Settings? You have to do both, in that order.

**Comment by MeYouGitHub** [comment]
I am getting the excact same error

**Comment by Johni0702** [comment]
Duplicate of #243
