### ISSUE TITLE
Bobby Wants to Upgrade Nothing

### ISSUE THREAD

**Issue by Obscure2020** [Johni0702/bobby#246]
I'm pretty sure `this world contains data from an old version` and `upgraded 0 chunks` are mutually exclusive ideas. When there are no chunks in the cache, and there is nothing to upgrade, Bobby should _**not**_ post anything in the chat, and it should _**not**_ offer to upgrade anything.

The following message should never happen. When there is nothing to upgrade, Bobby should say nothing, rather than recommending that you upgrade the nothing.

![2024-02-05_17 10 00](https://github.com/Johni0702/bobby/assets/69320464/28a09c5e-f694-4be0-84da-853d760bfc79)

**Comment by frozenMC** [comment]
Can also confirm this happens.

**Comment by MaledictYtb** [comment]
Same problem here.

**Comment by murphycd** [comment]
I have the same problem ("upgraded 0 of estimated 0 chunks").
It happens for me when Singleplayer Server View Distance is non-zero. Setting to zero removes the chat messages on world join (but but disables Bobby in singleplayer)
![image](https://github.com/Johni0702/bobby/assets/7470686/509f62f8-e3d0-4b96-80e8-212227653da3)

**Comment by Johni0702** [comment]
This can happen when the world metadata needs to be updated.

It should however not happen repeatedly.
If you have a world where it happens repeatedly, please attach your bobby config file and a zip of your `.minecraft/.bobby/<worldOrServer>` folder where this happens, as well as information on which specific Minecraft and Bobby version you're using.

**Comment by Johni0702** [comment]
Assuming everyone with this issue had "Dynamic World Management" enabled, this should be fixed in the just-released version 5.2.0.

If you did not have "Dynamic World Management" enabled, please open a new issue and include aforementioned details required for reproducing there.
