### ISSUE TITLE
Request: Above 32 Singleplayer Server View Distance (happy to help implement it)

### ISSUE THREAD

**Issue by tntcannon5000** [Johni0702/bobby#248]
Heya!

I've been experimenting with Bobby and I've noticed that the config slider does not allow for more than 32 chunks to be rendered from the players coordinates actively. 
If I attempt to manually edit the config file in .minecraft/config/bobby.conf to push past 32, it successfully shows the higher value in the bobby config panel, but does not actually increase the rendering radius beyond 32 ingame. 

Would it be possible to implement functionality for user-specified render radius above 32 in Singleplayer? 

I do have experience programming in Java so I would be happy to help/attempt to implement this if we could have a chat about it, I understand how busy people can be. 

I understand the consequences it would cause when using super high values, however, I am using Chunky to pre-render a vast swath of the world, and nvidium to render it, so the only piece of the puzzle missing would be this slider being able to go above 32. This would enable a functionally better implementation of Distant Horizons as distant chunks are still clearly rendered.

Do let me know

Thanks!!!!!!

**Comment by tntcannon5000** [comment]
Have found a way to force compat between Bobby and C2me, as the only issue is bobby ignoring config file values above 32 for view distance. However ,c2me is able to override the upper limit for view distance bobby uses. Hence, setting view limit to 512 in c2me allows bobby to use whatever singleplayer view limit is set in the config file.

**Comment by greenlentils850** [comment]
heya could you teach me to icrease render on single player? i dont have access to nvidium so is it still doable?

**Comment by Barkells** [comment]
Did you find anyway to get past this limit without using c2me?

**Comment by Johni0702** [comment]
The vanilla server has a hard limit of 32. One cannot simply increase the slider limit, that'll break all kinds of things.
Another mod like C2ME is required to go beyond 32 server view distance (and as you noticed, C2ME will override Bobby's override, so afaict there's nothing useful for Bobby to do here).
