### ISSUE TITLE
Disable saving loaded chunks to disk

### ISSUE THREAD

**Issue by SecretlyJealous** [Johni0702/bobby#25]
Is it possible to add some sort of option that allows me to load chunks beyond the view distance set by the server but not save them to the disk either? Optifine is able to achieve the same thing this mod does without saving the region file to the disk so I was hoping it would be possible to implement something similar in this mod. The problem I'm experiencing at the moment is that when playing on creative servers with large buildings the folder in .bobby becomes very large because it's storing region files for every area that I visit

**Comment by Johni0702** [comment]
Yes, removing that functionality should be fairly simple. My main use-case is on a (relatively) fixed size map, so I had not yet given much thought to disk usage.

It's quite the downgrade though cause just like Optifine (well, not exactly, there is an additional unloading delay in bobby) if you teleport away and then back (or reconnect), you'll have to run around to load stuff again.
So, depending on your use-case there may be better solutions, may I suggest one of:
- Automatically clear the .bobby cache on disconnect
- Automatically remove any region files which have not been accessed (or updated?) in the last X days (with the special case of 0, this also allows for essentially the same behavior as the other option)

**Comment by SecretlyJealous** [comment]
> Yes, removing that functionality should be fairly simple. My main use-case is on a (relatively) fixed size map, so I had not yet given much thought to disk usage.
> 
> It's quite the downgrade though cause just like Optifine (well, not exactly, there is an additional unloading delay in bobby) if you teleport away and then back (or reconnect), you'll have to run around to load stuff again.
> So, depending on your use-case there may be better solutions, may I suggest one of:
> 
> * Automatically clear the .bobby cache on disconnect
> * Automatically remove any region files which have not been accessed (or updated?) in the last X days (with the special case of 0, this also allows for essentially the same behavior as the other option)

Both of those solutions sound good to me :)
