### ISSUE TITLE
Not rendering more than 32 chunks

### ISSUE THREAD

**Issue by MeYouGitHub** [Johni0702/bobby#253]
I have set my max render distance to 32 and when comparing to 64 render distance there is no difference:

64 chunk render distance:
![64 chunk render distance](https://github.com/Johni0702/bobby/assets/159196071/6d07fa70-5652-4724-bf36-cb2a924f13a8)
32 chunk render distance
![32 chunk render distance](https://github.com/Johni0702/bobby/assets/159196071/d30c060d-c7af-455a-8343-34997555f07a)

Config file:
https://docs.google.com/document/d/16WdbWsjM1Tv0bzbH1EoAR8x2zGbYComou4hNb8EZJIo/edit

This is version 1.20.1 for fabric. I am also using Nvidium.
Is there any way to fix this?

**Comment by t-yuie** [comment]
just set the view-distance-overwrite to however many chunks you would like to load at once.

Additionally, are you using Mod Menu to access the config files? Because I cannot seem to find a way to do so.

**Comment by Johni0702** [comment]
Bobby isn't enabled in Singleplayer by default. You need to explicitly enable it first, see https://github.com/Johni0702/bobby/issues/110.

Do **not** set the view-distance-overwrite to however many chunks you would like to load at once. You may as well just not use Bobby at all at that point. See the explanation in the linked issue.
