### ISSUE TITLE
Bobby causes crash after sleep

### ISSUE THREAD

**Issue by 3ewalker** [Johni0702/bobby#254]
I've just installed Bobby, and it works most of the time. However, if my computer goes to sleep after some inactivity, Bobby crashes minecraft on launch. The only fix is a reboot of my computer.

[Crash Report](https://github.com/Johni0702/bobby/files/14394697/crash-2024-02-24_18.20.49-client.txt)

[latest.log](https://github.com/Johni0702/bobby/files/14394701/latest.log)

**Comment by Johni0702** [comment]
Some other, long-running program is leaking inotify watch registrations, such that at some point none are left (and any program which then wants to watch a file for changes will run into problems).
You can delay the issue [by increasing the limit](https://askubuntu.com/questions/770374/user-limit-of-inotify-watches-reached-on-ubuntu-16-04), though ideally you'd figure which program it is and report the issue to them.
