### ISSUE TITLE
Bobby for 1.20

### ISSUE THREAD

**Issue by itsAK14** [Johni0702/bobby#255]
i really want to use this mod but it has no support for mc version 1.20

**Comment by MaledictYtb** [comment]
Yes it does 
https://modrinth.com/mod/bobby/versions

**Comment by UnforseenDeath** [comment]
> Yes it does https://modrinth.com/mod/bobby/versions

he meant 1.20 not 1.20.1 or above.

**Comment by Johni0702** [comment]
Duplicate of #191
