### ISSUE TITLE
Bobby is having issues starting with optifabric again (1.20.2)

### ISSUE THREAD

**Issue by AvBlockgameEnjoyer** [Johni0702/bobby#257]
Hello, I am working on an un-official mod pack for blockgame (PirateSoftware Minecraft Server). Minecraft is giving the crash error 1 when I load it with optifabric file (optifabric-1.14.3.jar). I would like this to be fixed, however I know that y'all are busy doing fixes and what not, so I shall wait patiently until then. Make your days be filled with less bugs than before.

**Comment by Johni0702** [comment]
Duplicate of #208
