### ISSUE TITLE
Cannot configure bobby even with cloth-config (luanr client)

### ISSUE THREAD

**Issue by DafNuk** [Johni0702/bobby#258]
I somehow cannot configure bobby with cloth-config (fabric) on lunar client

If the problem is lunar client itself then ima feel very stupid

**Comment by Valox1ty** [comment]
I am having the EXACT same problem! it does not seem to be Lunar's problem as others are also missing the Config button despite having the latest Mod Menu Mod fabric

**Comment by Valox1ty** [comment]
one problem however could be the fact despite i downloaded it minecraft's directory is still missing the .bobby file, i will check into that and inform you if i find a workaround

**Comment by DafNuk** [comment]
> one problem however could be the fact despite i downloaded it minecraft's directory is still missing the .bobby file, i will check into that and inform you if i find a workaround

I just found a work around yesterday
heres how to do it
>open up appdata
>goto roaming
>goto .minecraft
>the bobby conf file should be below webcache2 (or just find the file named bobby)
>open it up with notepad or microsoft visual code software
>then set the render distance towrads your choice 
![image](https://github.com/Johni0702/bobby/assets/163662544/80f903d2-fd30-4698-ad63-d98f912b9aa0)
>then save and exit
and it should work on lunar client now

**Comment by Valox1ty** [comment]
thanks dude

**Comment by Valox1ty** [comment]
nope didnt work

**Comment by Valox1ty** [comment]
wait. mine was named bobby.config after i had renamed it to just bobby it reverted to 32 and i changed it to 250 and it worked

**Comment by Valox1ty** [comment]
thank you very much for the help, i appreciate it very much

**Comment by Hexergone** [comment]
it worked for me only when i play through the Minecraft launcher but when I use lunar (which id prefer) it doesn't work, do you know how to fix this?

**Comment by Johni0702** [comment]
You likely installed the Forge or NeoForge version of Cloth Config. Be sure to install the Fabric version, and for the correct Minecraft version.

If you are sure you have the correct version, please open a separate issue and attach the `latest.log` file (found in `.minecraft/logs/`).

If the issue only happens with Lunar, contact them for help; I cannot help you with their launcher.
