### ISSUE TITLE
5.1.0 does not work with OptiFine

### ISSUE THREAD

**Issue by GamerBossHarmon** [Johni0702/bobby#264]
Using 5.1.0+mc1.20.4 does not work on OptiFine 49.0.31 with OptiFabric 1.14.3

Also, using Fab 0.15.10 and FabAPI 0.97

OptiFine seems to be the problem, as when I start Minecraft with OptiFine off, it starts right up

[Log on Past.ee](https://paste.ee/p/UvE1X)
[Latest.log](https://github.com/Johni0702/bobby/files/14973578/latest.log)

**Comment by FarestR06** [comment]
OptiFine is notorious for its compatibility issues. I'd use something like Fabulously Optimized instead

**Comment by Johni0702** [comment]
Duplicate of #208
