### ISSUE TITLE
crashes on going through nether portal with high chunk unload delay

### ISSUE THREAD

**Issue by NoIDidntHackU** [Johni0702/bobby#268]
i have Nvidium and a few sodium mods installed and my render distance is 128 and my chunk unload delay is 480, bobby works fine when flying around my server normally, but as soon as I go through a portal with bobby my frames tank and then my game crashes, any idea why?

**Comment by NoIDidntHackU** [comment]
lowering chunk unload delay to 1 so that it renders chunks again fixes the issue but it's a bit annoying I can't have it higher

**Comment by Johni0702** [comment]
I'm guessing you're running out of RAM (either regular or GPU, or both) trying to load multiple dimensions at once at that render distance.
Can't tell you more without seeing the actual crash report.

**Comment by NoIDidntHackU** [comment]
the game doesn't actually crash, it just doesn't respond and I have to close it with Taskmanager

**Comment by NoIDidntHackU** [comment]
will have a look at the RAM

**Comment by NoIDidntHackU** [comment]
worked for me, thanks!
