### ISSUE TITLE
Game doesn't run

### ISSUE THREAD

**Issue by Sp7ki7zo77** [Johni0702/bobby#269]
I'm using prism launcher and using several of other mods, but when I enable bobbymod the game doesnt run and from the logs it seems to be a problem from bobbymod
[crash-2023-07-27_21.35.11-client.txt](https://github.com/Johni0702/bobby/files/15214030/crash-2023-07-27_21.35.11-client.txt)

**Comment by Sp7ki7zo77** [comment]
Full logs here 
[latest.log](https://github.com/Johni0702/bobby/files/15214032/latest.log)

**Comment by Johni0702** [comment]
This is caused by OptiFine. I have stopped supporting OptiFine because of stupid issues like this. I highly recommend using Sodium/Iris instead. See also https://optifine.alternatives.lambdaurora.dev/.
