### ISSUE TITLE
Mod doesn't have a config option when with mod menu

### ISSUE THREAD

**Issue by Typhlosho** [Johni0702/bobby#270]
i open minceraft with modmenu and bobby installed and in the mod menu there is no config option for bobby but a config option from the rest of the mods i have
i cant figure out why and some help would be appreciated, thanks.

**Comment by Xenapte** [comment]
Install ClothConfig

**Comment by VineTran1** [comment]
> Install ClothConfig

Installed the ClothConfig, still dont have config option.

**Comment by Johni0702** [comment]
Make sure to get the Fabric version of ClothConfig, not the Forge one.
