### ISSUE TITLE
Mod failing to load in 1.20.6?

### ISSUE THREAD

**Issue by muzikbike** [Johni0702/bobby#272]
May be the cause of issues like #271. There are obvious errors in the game log, and the render distance remains capped at 32.

[latest.log](https://github.com/Johni0702/bobby/files/15339352/latest.log)

**Comment by Johni0702** [comment]
The cause of the referenced issue is well know (see the reply on that issue; you need to enable Bobby for it to work in Singleplayer).
The only error in your log is about text2speech not working, which is a known issue with flatpak PrismLauncher and will happen even with no mods whatsoever.
