### ISSUE TITLE
Bobby not increasing render distance

### ISSUE THREAD

**Issue by GRcruiser** [Johni0702/bobby#280]
I'm using bobby and Nvidium but bobby isn't increasing the render distance on my single player worlds nor other servers I have fabric api, cloth config and sodium I have it set to 96 chunks and there isn't a difference it only removed the fog

Specs:
intel core i9 13900ks
RTX 4090 oc
64 gb ddr5

**Comment by Arya1234343** [comment]
you need to go to the chunks to have bobbymod save them and display them
