### ISSUE TITLE
[Help Needed] Bobby folder not created

### ISSUE THREAD

**Issue by SirBob27** [Johni0702/bobby#283]
Note: This is more of a tech support issue and likely not an issue with the actual mod. 

I've been using this mod for a long time, and after realizing that I had a typo in the IP of one of my Minecraft servers (Wynncraft, if you're wondering), I changed it and went to transfer the chunks. However, I then realized that there was no bobby folder within my minecraft folder. 

I don't exactly want to resort to reloading every chunk, so is there any way I can recreate my bobby folder to retrieve the chunks? Help would be greatly appreciated.

**Comment by Johni0702** [comment]
The `.bobby` folder should still be there. Make sure you're looking in the right folder, and if you're using an Operating System where files starting `.` are hidden by default, make sure hidden files are visible.
Changing the server address merely makes bobby look at a different subfolder. Unless you enabled the delete-after-x-time setting, Bobby will never delete it.

**Comment by SirBob27** [comment]
Thanks for the help, I didn't even know hidden folders existed.
