### ISSUE TITLE
Incompatible with 1.21 

### ISSUE THREAD

**Issue by J4PC** [Johni0702/bobby#284]
If you start your game, you get incompatible mods found, fabric pop up.
![image](https://github.com/Johni0702/bobby/assets/97805057/4f602614-7816-46d8-b23f-41340d6bd4e2)

**Comment by EmmanuelBeziat** [comment]
Well obviously, the mod was set for 1.20.6. We have to wait for a 1.21 release.

**Comment by Trackhe** [comment]
@EmmanuelBeziat its released since yesterday even for quilt. and the 1.21 release was 13.06.2024
many important mostly performance mods are already up to date.

**Comment by 4194304** [comment]
![wayland-screenshot-2024-06-14_19-10-23](https://github.com/Johni0702/bobby/assets/130800536/f5870911-0357-4af6-8e42-e3fc8375b4f4)
sometimes editing fabric.mod.json works but not here if that's one thing for sure

I guess distant horizons is out the window for today

**Comment by EmmanuelBeziat** [comment]
> @EmmanuelBeziat its released since yesterday even for quilt. and the 1.21 release was 13.06.2024 many important mostly performance mods are already up to date.

Hum, no? Last released version is still `bobby-5.2.0+mc1.20.6.jar`. There's a PR for a 1.21 compatible version, but it's not merged yet.

**Comment by Johni0702** [comment]
Released as Bobby 5.2.2 to GitHub, Modrinth and (once approved) CurseForge.
