### ISSUE TITLE
is it possible to update to 1.21 myself and rebuild it ? 

### ISSUE THREAD

**Issue by Mimibienv** [Johni0702/bobby#286]
is it possible to update to 1.21 myself and rebuild it ?

**Comment by ItzDerock** [comment]
Yeah, checkout PR #285 and run `./gradlew build`. Jar will be outputted to `./build/libs/bobby-5.2.0+mc1.21.jar` 

I've built a version and attached it: [bobby.zip](https://github.com/user-attachments/files/15858852/bobby.zip)

**Comment by ThisCatLikesCrypto** [comment]
i'm compiling it now, if it's successful i'll upload the jar

**Comment by ThisCatLikesCrypto** [comment]
> I've built a version and attached it: [bobby.zip](https://github.com/user-attachments/files/15858852/bobby.zip)

ty for the build, i tried myself but it didn't work

**Comment by Johni0702** [comment]
Duplicate of #284
