### ISSUE TITLE
Windows defender won't allow install due to virus with the 5.2.2 version

### ISSUE THREAD

**Issue by xdTiroj** [Johni0702/bobby#287]
I'm having this issue where I try to download the mod and windows tells me it won't allow me due to a virus being detected.

**Comment by Arya1234343** [comment]
just click allow anyways. it should work

**Comment by Johni0702** [comment]
Assuming you're downloading it from one of the official sources, and there isn't actually is a virus in there (meaning it's just another false positive, of which I've by now gotten so many that [alarm fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue) has long set in), there's nothing I can do about that.
You need to complain to Microsoft about it.
