### ISSUE TITLE
Lighting on some chunks are too bright or too dark

### ISSUE THREAD

**Issue by EquityX** [Johni0702/bobby#290]
The areas circled in red appear with just bobby enabled. The areas circled in green appear when nvidium is enabled alongside bobby. Random chunks flicker black/transparent when moving & gets worse with more speed. None of the issues happen with bobby disabled. The pack is Fabulously Optimized 6.0.0-beta.1 for 1.21 with C2ME, Bobby, & Nvidium added. Bobby's Singleplayer Server View Distance is set to 12. Render distance is set to 32. The error is most visible flying over water.

![Chunks during movement](https://github.com/Johni0702/bobby/assets/20719360/68952bd6-8963-4a30-b9c1-473ab7cc9194)
![Dark chunks](https://github.com/Johni0702/bobby/assets/20719360/06d6ad50-669d-47ea-894d-38a56fa5c3d3)
![Bright Chunks](https://github.com/Johni0702/bobby/assets/20719360/5b79b717-bc80-435f-ad3d-c0e272edfa7f)

**Comment by Johni0702** [comment]
Are these consistently in the same places or do they move around every time you load that area / enter the world?
Does it also happen when you do not install **any** other mods?
And when you say "enabled", do you mean in the settings or put moving the mod jar in/out of the mods folder? Only the latter really counts; stuff that's still in the mod folder can still have effects on the game even if its primary functionality isn't enabled.

**Comment by EquityX** [comment]
I disabled/enabled mods by moving them in/out of the mod folder. I tested Bobby with no other mods & the visual bugs still occurred with the exception of the lighter chunks that only happen with nvidium. The affected chunks seem mostly random but sometimes look like they line up with Bobbys Singleplayer Server View Distance.
