### ISSUE TITLE
Doesn't Work 

### ISSUE THREAD

**Issue by StinkyMcDinky** [Johni0702/bobby#293]
![Screenshot (4)](https://github.com/Johni0702/bobby/assets/174753932/e5e7408f-cf24-4c91-a762-7213bdaaa5f3)
![Screenshot (6)](https://github.com/Johni0702/bobby/assets/174753932/cd605f0a-9dae-44a9-a8b5-04ae8f0b8a27)
![Screenshot (8)](https://github.com/Johni0702/bobby/assets/174753932/73421437-34e3-49d6-bce5-1c9c7adbb425)

**Comment by Jai2457** [comment]
Howd you fix it?
