### ISSUE TITLE
Loading visible chunks outside of max server loading distance

### ISSUE THREAD

**Issue by Felix14-v2** [Johni0702/bobby#30]
It would be nice if bobby optionally could forcefully generate/load chunks outside of the server's load distance, and then immediately unload them, leaving them only visible. Is it possible to make such an option?

**Comment by mkb2091** [comment]
There is already the option of having a fallback world which will be used if you haven't recieved those chunks from the server. You could either fly around or use a pregenerating chunks mod to generate the chunks in the fallback world, so they would already be visible when you go on the server

**Comment by Felix14-v2** [comment]
Indeed, I forgot about this... It's not as convenient as it could be, but it suits my purposes. Thank you!
