### ISSUE TITLE
MC 1.21: Boddy is not working, I can only see 32 chunks

### ISSUE THREAD

**Issue by WilliamVercken** [Johni0702/bobby#310]
Hi! I can't see more than 32 chunks in my test.

Here is my modpack with only Fabric and Bobby:
![image](https://github.com/user-attachments/assets/8b64bbec-840e-4028-ac42-4c00ee4fdde8)

Here is my config file where I only modified `max-render-distance=100`

```
# Delete regions from the cache when they have not been loaded for X days.
# 
# The cache for a given world is cleaned up whenever you disconnect from the server.
# Entire worlds are cleaned up when the game starts and you have not visited them for X days.
# 
# Set to -1 to disabled.
# Set to 0 to clean up everything after every disconnect.
delete-unused-regions-after-days=-1
# Enables support for servers with multiple identically-named worlds.
# 
# When enabled, a new local cache is started on each world change. If there are enough chunks with similar content in two caches, they will automatically be merged.
# This does mean that you may need to walk around a little before Bobby loads in cached chunks if there is little identifying information in your world (e.g. flat worlds).
# 
# You may need to delete your existing cache if it is comprised of multiple worlds to prevent Bobby from merging into it.
# Requires a `/bobby upgrade` after enabling with existing cache.
dynamic-multi-world=false
enabled=true
# Changes the maximum value configurable for Render Distance.
# 
# Requires Sodium.
max-render-distance=100
# Do not load block entities (e.g. chests) in fake chunks.
# These need updating every tick which can add up.
# 
# Enabled by default because the render distance for block entities is usually smaller than the server-view distance anyway.
no-block-entities=true
# Reduces the light levels in fake chunks so you can tell the difference from real ones.
taint-fake-chunks=false
# Delays the unloading of chunks which are outside your view distance.
# Saves you from having to reload all chunks when leaving the area for a short moment (e.g. cut scenes).
# Does not work across dimensions.
unload-delay-secs=60
# Overwrites the view-distance of the integrated server.
# This allows Bobby to be useful in Singleplayer.
# 
# Disabled when at 0.
# Bobby is active in singleplayer only if this is enabled.
# Requires re-log to en-/disable.
view-distance-overwrite=0
```
Here are my video settings:
![image](https://github.com/user-attachments/assets/28bd7ebc-ef2c-4fec-a241-60facb1cb6e1)

Here is the rendering distance at 100 :
![image](https://github.com/user-attachments/assets/42a99557-e89f-4749-acbe-a67ed0c779fc)

Here is the rendering distance at 32:
![image](https://github.com/user-attachments/assets/b4705594-0a9e-41e2-a373-f52e8c14e1c1)

Here is the village (I already visited, so the chunk should be cached) I should able to see if the mod worked on my setup:
![image](https://github.com/user-attachments/assets/7b3c8882-6557-41c9-9728-38edc13c47a1)

What can I do? Am I missing something?
Thank for your help!

**Comment by WalkingGlitch** [comment]
I'm having the exact same issue. I can set it above 32 chunks, but it simply doesn't load or render them. This is also on a single player world, so it's not a server view distance issue.

**Comment by WalkingGlitch** [comment]
`view-distance-overwrite=0`

This should be set to 1. In my case though, it just breaks the game because it doesn't load any chunks anymore.

**Comment by WilliamVercken** [comment]
Thank you @WalkingGlitch , that's what I needed!
I didn't set it to one because I would only generate chunks near me, but setting it to 32 solves the problem, thanks a lot!

**Comment by WalkingGlitch** [comment]
> Thank you @WalkingGlitch , that's what I needed! I didn't set it to one because I would only generate chunks near me, but setting it to 32 solves the problem, thanks a lot!

I thought it was a boolean. That explain why it wasn't working for me. Thanks for inadvertently helping with my problem as well. 😅
