### ISSUE TITLE
Bobby 5.2.4 Not Marked As Compatible With 1.21.1 on Modrinth

### ISSUE THREAD

**Issue by anv-sh** [Johni0702/bobby#316]
## Issue Description
As mentioned in the title, Bobby 5.2.4, while compatible with 1.21.1, is not marked as compatible with 1.21.1 on Modrinth. This unfortunately breaks mod downloader/updaters, such as Prism Launcher's mod downloader/updater, which rely on marked valid versions to determine whether a mod is available for the currently installed Minecraft version or when a mod update is available for that version. This forces users to adjust filters for major versioning only while downloading, and prevents automatic updates.

### A Note of Appreciation
That being said, thank you so much for creating and continuing to maintain this mod. It has allowed myself and friends of varying hardware and network environments to all be able to enjoy multiplayer together, with no one needing to make a compromise. We are all eternally grateful for the hard work you've put into this project.

**Comment by GamerGuyD3** [comment]
Thank you for commenting this! I wasn't even going to try using it in 1.21.1 until I saw this message, so much appreciated!

But yeah this needs to be done. People can't be left out on such an amazing mod!
