### ISSUE TITLE
it wont work on lunar

### ISSUE THREAD

**Issue by Flippy101** [Johni0702/bobby#319]
i installed bobby into lunar mc version 1.21 and it just wont work, i installed the cloth config mod and the mod menu and i cant config bobby, if i enter mod menu i just see bobby there with its description, no config button, can anyone please help me?
![image_2024-09-10_162322771](https://github.com/user-attachments/assets/90b2a8cd-a09e-4b95-bd2e-f3d55d4a8717)
![image_2024-09-10_162427721](https://github.com/user-attachments/assets/e376179f-43b9-4637-b924-2f2ab7b4f35f)
and yes i tried with the other fabric API mod that is shown in the 2nd photo it still doesnt work

**Comment by Johni0702** [comment]
Complain to Lunar.
