### ISSUE TITLE
Broken in older versions

### ISSUE THREAD

**Issue by fatih1d** [Johni0702/bobby#321]
Bobby is broken in old servers  like uses 1.5.2 and older while it works fine on newer versions. When i join a 1.5.2 server, the mod works and shows chunks more than servers view-distance setiting, but theres a void between chunks and when i fly, the void shows off and creates again on another place. If i turn off Bobby, theres no voids and its normally. It just shows voids that doesnt even exist. My game version is 1.20.4 and the server also supports versions like 1.20.4 while its 1.5.2
Screenshots below. 
![2024-09-15_15 21 21](https://github.com/user-attachments/assets/bf227eea-abeb-41d3-81e4-7cc5228851e4)
![2024-09-15_15 20 38](https://github.com/user-attachments/assets/020924b0-d683-41d4-9478-3f38632cdfae)
![2024-09-15_15 20 49](https://github.com/user-attachments/assets/e16a2a8f-d5d0-4331-9f5e-2a2876616a6a)
![2024-09-15_15 21 15](https://github.com/user-attachments/assets/1aa36dff-04aa-4b4c-874a-bca16fac5a35)
![2024-09-15_15 20 19](https://github.com/user-attachments/assets/5b56b93e-49e5-4169-af8f-dfd8e145640e)
![2024-09-15_15 20 27](https://github.com/user-attachments/assets/7ce679be-f59b-4763-a3b1-0a6010dfb27d)

**Comment by MaledictYtb** [comment]
How do you even join 1.5.2 servers ?

**Comment by Johni0702** [comment]
I'm assuming whatever compatibility plugin allows you to join with such a hugely different version is actually actively adding an empty outer row of chunks to get the client to properly render all chunks. Modern clients by default will not render chunks that don't yet have any neighbors, hence why such an empty row of chunks would be necessary.

And if the server is sending an empty row of chunks, then the game showing an empty row of chunks is correct behavior, so nothing Bobby can really do here.
