### ISSUE TITLE
Server Networks

### ISSUE THREAD

**Issue by DevMC7** [Johni0702/bobby#327]
Let's say you are on a network. You are on the lobby, and you click an NPC to play a minigame. The chunks bobby would generate around the minigame's map are the lobby's chunks, not the minigame's chunks. This can be fixed by adding additional folders for velocity/bungeecord networks which will store the chunks of all the other servers on the network

**Comment by DevMC7** [comment]
By the way this was in 1.21

**Comment by Johni0702** [comment]
Bobby already stores separate worlds in separate folders. The issue with certain server networks is that they give the client the same world name for conceptually different worlds, so as far as the client is concerned, it actually is all the same world.
For these servers, you need to enable the `Dynamic World Management` feature in its config, it'll then no longer trust what the server says and instead try to match up worlds with ones it has seen previously based on the blocks around it.
