### ISSUE TITLE
Crash on 1.21.1 game boot

### ISSUE THREAD

**Issue by corp-thunder** [Johni0702/bobby#331]
bobby crashes on 1.21.1, i attached the crash log and latest log

[crash-2024-10-29_06.57.59-client.txt](https://github.com/user-attachments/files/17552359/crash-2024-10-29_06.57.59-client.txt)
[latest.log](https://github.com/user-attachments/files/17552361/latest.log)

**Comment by Johni0702** [comment]
Delete `.minecraft/config/bobby.conf`. Something has corrupted it to be all 0s.
