### ISSUE TITLE
Completely bricks when trying to join world

### ISSUE THREAD

**Issue by notanaverageguy** [Johni0702/bobby#333]
https://github.com/user-attachments/assets/d0e7e004-11b3-421f-b3ad-d2e20b36e58a

[2024-11-01-7.log.gz](https://github.com/user-attachments/files/17605123/2024-11-01-7.log.gz)

**Comment by notanaverageguy** [comment]
i understand that its hard to debug from this but here's what i've tried doing,
deleting .bobby folder
deleting bobby config
removing all other mods
going into the world files and deleting any extraneous files
deleting the fabric data folder

**Comment by Johni0702** [comment]
The name of your world contains a `:` which Windows does not allow in file names.
Bobby 5.2.0 will correctly handle this, so either update to Minecraft 1.20.6 or above, or rename your world to not contain characters which Windows doesn't like.
