### ISSUE TITLE
dont have an setting of the top right in mod menu

### ISSUE THREAD

**Issue by lighth92** [Johni0702/bobby#334]
i'm in lunar client right now, and i dont see the mod menu when i go to the bobby mod tab, there is no settings in top right corner, its just blank, and my render settings is still at 32 because there is no mod settings for it to change the  render
![bobbymod](https://github.com/user-attachments/assets/1f0a70fc-03aa-4bd2-8d6f-9073562f368d)

**Comment by Johni0702** [comment]
> For an in-game config screen, install [ModMenu](https://modrinth.com/mod/modmenu) and [ClothConfig](https://modrinth.com/mod/cloth-config).

You're missing ClothConfig (or have installed the Forge version instead of the Fabric version).
