### ISSUE TITLE
I can't open bobby settings

### ISSUE THREAD

**Issue by StarkerRegen12** [Johni0702/bobby#338]
![Nicht funktionieren](https://github.com/user-attachments/assets/ff6504a7-a6ac-4dae-b6fd-45c34ad75e6f)
  

does anyone now why i cannot go to the settings and change the render

**Comment by Reelix2400** [comment]
Yes i have the same broplem

**Comment by gamelamp** [comment]
> ![Nicht funktionieren](https://private-user-images.githubusercontent.com/188275907/385526719-ff6504a7-a6ac-4dae-b6fd-45c34ad75e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzEyMjEsIm5iZiI6MTczMjEzMDkyMSwicGF0aCI6Ii8xODgyNzU5MDcvMzg1NTI2NzE5LWZmNjUwNGE3LWE2YWMtNGRhZS1iNmZkLTQ1YzM0YWQ3NWU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxOTI4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzU4M2YxNTBhMjUzOTMzODU3NmNhMzM1NzJiZGYxNDA3MDAzMTk1YTEyMTdmYTk2MTQ0YTAzYTgzM2I1NzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m8mWBb4h3nQ21PrhfWZr-B4NmVVAAIHs_5VS0VAei68)
> 
> does anyone now why i cannot go to the settings and change the render

The answer is simple;
you need to install cloth config as well

**Comment by StarkerRegen12** [comment]
Bro i allready have the mods tha are needed but still dosnt Work

**Comment by gamelamp** [comment]
> Bro i allready have the mods tha are needed but still dosnt Work

show us your modlist

**Comment by Alfred201018** [comment]
hey, i got the same problem but i already have cloth config

**Comment by Johni0702** [comment]
From the README:

> For an in-game config screen, install [ModMenu](https://modrinth.com/mod/modmenu) and [ClothConfig](https://modrinth.com/mod/cloth-config).

If you don't have the button in ModMenu, you're missing ClothConfig (or have installed the Forge version instead of the Fabric version).
If you do have the button but clicking it doesn't work / crashes the game, attach the `.minecraft/logs/latest.log` file.
