### ISSUE TITLE
Render distance limited to 32 chunks, even with Sodium?

### ISSUE THREAD

**Issue by googleooer** [Johni0702/bobby#39]
I tried using both saved server chunks and a bobby-fallback world. I set the max render distance to 72 in the settings file, but chunks just stop loading where they would stop loading if the render distance was set to 32.

**Comment by googleooer** [comment]
Nevermind, it's weirder than that. It seems like it only works with server chunks, but I have to fly away for it to work. It doesn't load bobby-fallback's chunks past 32 chunks.

**Comment by Johni0702** [comment]
> I set the max render distance to 72

But did you also change the actual render distance? The bobby setting only controls the max value for that slider, it doesn't change it.

**Comment by googleooer** [comment]
Yes, I set it to 64 but only server chunks loaded

![github_1](https://user-images.githubusercontent.com/35429559/126081690-3c671c9a-0c15-4d12-a174-6885e53a4bb0.png)

**Comment by Johni0702** [comment]
Oh, I see. I misunderstood when you said you used both [server chunks and fallback at the same time] and took it to mean you tried both options and the issue existed with both.

So, does it load anything from the fallback storage at all? There exists no 32 chunks limit anywhere in the fake chunk management code, so parts of it cutting off after 32 seems arbitrary, parts of it not working at all seems more plausible.
Can you share a screenshot of the renamed world folder?

**Comment by leucome** [comment]
I have  a similar issue the chunk from the bobby-fallback world do not load. I can only get chunk I explored while connected to the the server. 
So I thought maybe the fallback do not work at all.  I am not even sure where bobby-fallback folder is supposed to be placed. 

But maybe it kinda work,  when I explore on the server these chunk seem to load faster than usual.   It is almost like it load the fallback chunk but only in the server view range  until they get replaced by the one from the server few second later.

I also tried to overwrite all the chunk directly in .bobby/"serverip" folder with all the already generated one. Same they wont load unless I explore them.

**Comment by jw-taylor** [comment]
Yes, where is the fallback folder meant to go?

**Comment by Johni0702** [comment]
Closing in favor of #43.
Please check if any of my suggestions there apply and if they do not, reply over there with a detailed description of your issue (including how you've determined that none of the suggestions apply) and a corresponding log.
