### ISSUE TITLE
Bobby conflicts with new version of C2ME (0.2.0+alpha 4)

### ISSUE THREAD

**Issue by Carterpersall** [Johni0702/bobby#48]
Yesterday C2ME released a new version that is now crashing when clicking on video settings if paired with Bobby. My best guess for why this is happening is because in this version C2ME added a new no-tick view distance. 
See https://github.com/ishlandbukkit/C2ME-fabric/issues/56 for more information as there is an issue already open on the C2ME github.

**Comment by Johni0702** [comment]
Your guess is correct, both mods do exactly the same thing: They increase the max value of Sodium's render distance value.

Not sure what the best to resolve this is. I only recently learned that [`@ModifyConstant` is not actually composable](https://github.com/SpongePowered/Mixin/issues/516). I guess either (or both) mods could switch to a ModifyVariable if the method permits it (I don't actually recall what the corresponding code looks like), or we could wait for there to be a composable option for ModifyContant and then use that (and ofc make sure our overwrites actually compose), or one of them could disable their overwrite in the presence of the other.
So I'm going to wait for the opinion of C2ME's author.

In the mean time, you should be able to work around this relatively easily by opening either (but not both) mod jar and editing their "*.mixins.json" file (`bobby.mixins.json` or `c2me.client.mixins.json`) to remove the `SodiumGameOptionPages` entry, and then the other mod's overwrite will be applied as usual.

**Comment by Carterpersall** [comment]
The most recent commit on C2ME supposedly fixes the conflict

**Comment by Johni0702** [comment]
Closing as this should be fixed as of C2ME 0.2.0+alpha5.
