### ISSUE TITLE
Can't load chunks saved using bobby as a single player world.

### ISSUE THREAD

**Issue by Franck-Nein** [Johni0702/bobby#49]
After moving the region files created using bobby into a single player world, when you load the world all chunks get regenerated, if spectatorsGenerateChunks is set to false the chunks just don't load.
The log just says
[23:32:53] [Server thread/ERROR]: Chunk file at [X, Y] is missing level data, skipping
for every chunk loaded.
Opening the world in [minutor](https://github.com/mrkite/minutor) or [amulet](https://github.com/Amulet-Team/Amulet-Map-Editor) does work properly.
Using bobby 2.0.4 and Ubuntu 20.04.

**Comment by Johni0702** [comment]
Bobby is not a world downloader. It uses region files as the storage medium purely for convenience and so no extra code is needed to load from a fallback world. There is a lot missing from bobby's cache that would be required to be able to load it as a regular world.
