### ISSUE TITLE
Not able to join server with different port number

### ISSUE THREAD

**Issue by DriftingZero** [Johni0702/bobby#5]
Joining a server that uses an IP address with a non-default port number (i.e. 127.0.0.1:25593) would produce this error and keeps you from joining said server

https://pastebin.com/40FXhkPB
(This client is heavily modded and Not Enough Crashes is also part of the mods)

**Comment by U5B** [comment]
https://pastebin.com/4UzJ2vvr

Can confirm that it happens on my machine. However it seems to print a different error on my end. I tried to connect to hypixel using mc.hypixel.net:25565. Connecting to mc.hypixel.net worked just fine.

**Comment by DriftingZero** [comment]
> https://pastebin.com/4UzJ2vvr
> 
> Can confirm that it happens on my machine. However it seems to print a different error on my end. I tried to connect to hypixel using mc.hypixel.net:25565. Connecting to mc.hypixel.net worked just fine.
> 
> EDIT: My log is the obfuscated classes, his is unobfuscated.
> 
> EDIT 2: https://paste.gg/p/anonymous/294b346347944861811d668c93cb24e8 this is with Not Enough Crashes installed

It gives a long spam of errors in the log. I just picked the first error that show up when I joined the server.

**Comment by pyrestriker** [comment]
I will concur, this happens with both releases. Trying to connect to my SMP and it stalls out and now I have a logfile almost 50 MB. The port is 25567. Too large for pastebin... https://drive.google.com/file/d/1epeKMIZcge-XMAZaGGZ83iASEthiVWS8/view?usp=sharing

**Comment by ioanvl** [comment]
Had the same issue as well. I -assume- it has to do with the colon ( : ) being an 'illegal' character for folder names. 
From what I noticed the local caches are stored in folders named after the server addresses, that  contain colons ":" in the case of different ports.
