### ISSUE TITLE
Render errors + Black Chunks.

### ISSUE THREAD

**Issue by Trirez** [Johni0702/bobby#60]
Mods: Sodium beta alpha 5 and latest bobby 3.0.0
Showing black chunks and constant render errors and also server gone very slow when using it.
[Error log.txt](https://github.com/Johni0702/bobby/files/7687269/Error.log.txt)

**Comment by Johni0702** [comment]
Starlight is afaik currently not compatible with Sodium, I'm guessing that's your "constant render errors".
It's also been incompatible with bobby for a while, that's the black chunks, see #18.

> and also server gone very slow when using it.

Idk what exactly that's supposed to mean but bobby does not (and cannot possibly) affect your server.
