### ISSUE TITLE
Render distance reverts to 32 in 1.18.1

### ISSUE THREAD

**Issue by Chiss5618** [Johni0702/bobby#61]
Whenever a render distance in slider is set past 32, it reverts back to 32 after exiting the screen. Using newest version of sodium, and the only other mods are iris, sodium, cloth config and mod menu. Render distance in config file is set to 128.

**Comment by Biscuts511** [comment]
this isnt a bobby specific issue, in 1.18 and earlier you could manually set the render distance higher in the config file. as of 1.18.1 any value greater than 32 is reset to 32.

**Comment by Johni0702** [comment]
And you can still do this with Bobby + Sodium by setting the max render distance in Bobby's config.

**Comment by Biscuts511** [comment]
Unless the replay mod specific version of sodium changes something important (it might I am quite thick skilled) when I change the max in the config to 64 for example it changes the max in the sodium setting, when I try to change it it gets reverted to 32 however

**Comment by Johni0702** [comment]
Are you using any other mods? I cannot reproduce any such thing on my machine.
Also, just to make sure your expectations aren't incorrect: What specific value are you changing (or have changed) where and at which specific point does what specific thing revert to 32? Ideally with screenshots so it's clear we're not talking about different things.

> Unless the replay mod specific version of sodium changes something important

It doesn't.

**Comment by Biscuts511** [comment]
![Screenshot_20211213_091920](https://user-images.githubusercontent.com/74526781/145867072-f7d50d71-c851-432c-b195-d2b5d8f93d97.png)
![Screenshot_20211213_091952](https://user-images.githubusercontent.com/74526781/145867081-481952fc-91ac-4a34-afaa-f1b15c8d653f.png)
![Screenshot_20211213_092005](https://user-images.githubusercontent.com/74526781/145867088-f53e70a9-08e3-4943-a41e-c2eb68cad9d1.png)
![Screenshot_20211213_092013](https://user-images.githubusercontent.com/74526781/145867095-07320605-d552-46a1-ac8c-d3f7a7d945b3.png)
![Screenshot_20211213_092023](https://user-images.githubusercontent.com/74526781/145867103-9a1979db-016c-4327-9cb9-d53e30114a7f.png)

I have the maximum render distance set to 64 in bobby config, when I try to change it in video settings (screenshots) it is reset to 32 as soon as I exit the video settings page.

mods:
Bobby 3.0.0
fabric api 0.44.0
iris 1.1.3
sodium (replay compatable) rc1-0.4.0-alpha5+rev.7c0c941

I will try it with normal sodium in a minute

**Comment by Biscuts511** [comment]
I just confirmed the behavior with the sodium version on curseforge.

I could try compiling it from the source, tho I feel like the cause might be something else.

There is also a likely possibility that this is an issue with either Linux (arch w/ custom xen-rog kernel) or with Multimc (needed to get my d-GPU to render the game)

**Comment by Johni0702** [comment]
It's probably none of these things. I'm running MultiMC on Debian with a custom Sodium built from RM's source. Only thing I'm not running is a d-GPU and a custom kernel.

**Comment by Biscuts511** [comment]
> d-GPU (whatever that is)
d-gpu = nvidia card 

when I use the "official" Minecraft launcher it uses my i-GPU (AMD integrated graphics) 

it could be weird arch things, arch isn't officially supported and it causes issues ( I don't use gnome so it doesn't save the Microsoft login keys as it only saves to the gnome-keyring)

**Comment by Johni0702** [comment]
Oh, this doesn't happen in 1.18. It happens in 1.18.1, and 1.18.1 only, even with the same mods.

**Comment by Biscuts511** [comment]
Ok cool, I'm not imagining things.

Is there a place I could compare the code for 1.18 and 1.18.1 to try to find the exact change that caused this?

**Comment by Johni0702** [comment]
Easiest way to do that is to setup a Fabric development environment for both and then look at the classes. Since I've already got that for Bobby, here's the change, idk why they felt the need to do that in a point release: 
![](https://i.johni0702.de/9SKW1.png)
I'll fix it in a minute by also allow >32 for vanilla (didn't do that to begin with because it's basically unplayable, but there are other mods which improve it, e.g. #29 so it's on my list of things to add anyway).

**Comment by Biscuts511** [comment]
ok, cool that it was that easy, ill probably set up a dev environment eventually :)

**Comment by keplergray** [comment]
I'm still getting this issue on 1.18.1 with Bobby 3.1.0.

When I enable the DistantHorizons mod alongside Bobby the bug is fixed and the render distance saves properly.
