### ISSUE TITLE
Bobby doesn't seem to work in SP or MP(1.18)

### ISSUE THREAD

**Issue by ImMrLemons** [Johni0702/bobby#62]
I've always had issues with this mod even back in older versions, but with 1.18 it doesn't want to work at all. I believe in 1.17 I was able to get it working in MP, but SP never seemed to work even with "bobby-fallback". Now even in my server the chunks never seem to properly render as low res when I leave my render distance. The .bobby folder is filling up as I move around my SP world and my MP server, however I never see them in game.

**Comment by Johni0702** [comment]
Are you using any other mods?
Been a while since I've tried the "bobby-fallback" feature (I don't use it myself), but regular caching should definitely be functional.

> the chunks never seem to properly render as low res when I leave my render distance

wdym? chunks aren't supposed to be low res, this isn't a Level-of-Detail mod. And how do you leave your own render distance?

**Comment by ImMrLemons** [comment]
Sorry for the confusion, for whatever reason I started fiddling with the settings and it appears to work now on my server. Been a while since I used these mods like this so I think I merged Bobby and FarPlanes together in my head which is why I mentioned the "low res" textures. Thank you and great work! :)
