### ISSUE TITLE
Chunks fail to load, patchy chunk loading when Bobby is enabled in my mod stack

### ISSUE THREAD

**Issue by giorov** [Johni0702/bobby#65]
Chunks fail to load, patchy chunk loading when Bobby is enabled in my mod stack. 

I've also had bobby cache get corrupted entirely, having to delete the .bobby folder to get it to load chunks again on Wildercraft.

Any chance you could check the mod out with these on? 
![image](https://user-images.githubusercontent.com/37343119/146690072-8552d5ba-45a7-4992-afb7-892e719413eb.png)
![2021-12-19_12 35 32](https://user-images.githubusercontent.com/37343119/146690079-bdb2f54c-4113-49d9-ac5d-455fc92c82d8.png)

**Comment by giorov** [comment]
Not sure if this is related to being able to teleport on Wildercraft tree servers, probably not. If I just fly around, some chunks load in, some don't.

**Comment by Johni0702** [comment]
Please try to narrow down which mods are required to reproduce this by removing as many as possible. My guess would be that it's one of Xaero's mods cause they necessarily touch chunks and are the only big ones I've never used myself.

Once done, please attach the `latest.log` file (you can also take a peek in there right now for hints as to which mod might cause it), as it may contain further info on what's going wrong.
It'd also be good to know if the missing chunks and their immediate neighbors are loaded: Do you get the outline when looking at where a block should be? Does the F3 menu show "Waiting for chunk" if you're standing inside them?
Please also check if you can reproduce it is singleplayer or in replays (ReplayMod), so I've got some way to reproduce it without having to run around on that server.

**Comment by giorov** [comment]
It's related to Sound Physics which is in beta.

I get an outline of where blocks would be. F3 does not show "Waiting for chunk."

I get these errors in the latest.log:

**Comment by giorov** [comment]
I'll report this to the Sound Physics GitHub issue tracker.

**Comment by giorov** [comment]
If you want to look over the log yourself... [latest.log](https://github.com/Johni0702/bobby/files/7744030/latest.log)

**Comment by giorov** [comment]
SoundsPhysics maker says...
![Screenshot 2021-12-20 214148](https://user-images.githubusercontent.com/37343119/146877555-6b70ba99-7951-4b04-978f-f77ba7cef063.png)

**Comment by Johni0702** [comment]
As per above linked issue, this should be fixed with SoundPhysics' latest release as of Jan 21, 2022.
