### ISSUE TITLE
Setting the render distance to 128 chunks results in new chunks not being loaded from multiplayer servers 

### ISSUE THREAD

**Issue by akemin-dayo** [Johni0702/bobby#71]
While it is _definitely_ silly to try to render at such a high draw distance (due to obvious performance issues), this is still a bug that should be fixed.

Bobby's locally-cached chunks will still load from disk, but any new chunks (or even updated chunks in existing cached areas) will not load.

It seems to me that something is overflowing somewhere, as setting the draw distance to _127_ chunks will result in working behaviour.

This issue appears to be specific to Bobby (and not Sodium), as this behaviour does not occur in singleplayer worlds.

For reference, I'm seeing this behaviour on 1.18.1, Bobby 3.1.0.

**Comment by Johni0702** [comment]
> 1.18.1, Bobby 2.1.0.

That's not a valid combination, Bobby 2.x is for MC 1.17.x

I also can't reproduce the problem. I set my render distance to 128 and chunks still update fine when I walk around, they also load fine when I clear my cache. Bobby doesn't really have any size constraints anywhere, the smallest numbers in use within bobby are packed section positions, but those are still 22 bits (that's 4kk blocks / 262k chunks).
https://paste.ee/p/p3E26 (Sodium version is a custom one based on 0.4.0-alpha5, optimized for high render distances)

> This issue appears to be specific to Bobby (and not Sodium), as this behaviour does not occur in singleplayer worlds.

I don't see how one follows from the other. SP has a hard limit of 32, so you can't get 128 chunks radius loaded there in the first place.

> While it is definitely silly to try to render at such a high draw distance (due to obvious performance issues)

Debatable. Not ideal but still playable (with the custom sodium anyway):
![](https://i.johni0702.de/Jsj31.png)

**Comment by akemin-dayo** [comment]
> That's not a valid combination, Bobby 2.x is for MC 1.17.x

Oops, made a typo there — it was 3.1.0.

Anyway, I figured it out — I accidentally left Farsight enabled when testing, which was what was causing the issue to occur.

Closing this issue as it's not a Bobby issue.

(Also huh, I didn't know the max draw distance of the integrated server was 32. The more you know, I guess…)
