### ISSUE TITLE
Render Distance resets to 32 chunks in 1.18.1

### ISSUE THREAD

**Issue by Dekoderio** [Johni0702/bobby#75]
In bobby-3.1.0 in 1.18.1 if you try to set render distance to more than 32 chunks it will just go back to 32 with sodium. Without sodium it will go higher, but it won't affect visual render distance. Installed only bobby, cloth config, sodium and mod menu.

**Comment by Johni0702** [comment]
How are you setting the render distance? Please screenshot bobby's config screen.

**Comment by Dekoderio** [comment]
![Minecraft Screenshot 2022 01 25 - 15 20 30 87](https://user-images.githubusercontent.com/49859200/150938651-de07e0b9-3e1c-4b8b-a53b-b43fbe7bdbd2.png)
Then slider in video settings allows to go higher than 32, but when I apply the changes and go back to video settings value resets to 32

https://user-images.githubusercontent.com/49859200/150938961-dbda9da3-ee20-4cf9-82f3-f59077109340.mp4

.

**Comment by Johni0702** [comment]
Hmm, that is a bug that existed in 3.0.0 but I fixed it in 3.0.1 and I cannot reproduce it with 3.1.0 either.
Could you attach your `latest.log` file after that happens? Maybe there's a hint in there.

**Comment by Dekoderio** [comment]
[latest.log](https://github.com/Johni0702/bobby/files/7932172/latest.log)

**Comment by Dekoderio** [comment]
Oh... For some reason when I logged into a game now, render distance changed as it supposed to... I have no idea why though, I tried relogging before...

**Comment by Dekoderio** [comment]
Found out what it was... When I relogged before, I was resseting Bobby's max render distance (idk why I did this). When you relogg into the game with already changed distance it works fine. Didn't think about it, because it doesn't say about relogging when changing this setting anywhere. Sorry for taking your time, it was my mistake, should've tried it.
