### ISSUE TITLE
Add support for 1.19

### ISSUE THREAD

**Issue by SecretlyJealous** [Johni0702/bobby#98]
1.19 has been released, hopefully you can update it whenever you get the chance

**Comment by Logan9312** [comment]
Agreed, this would be nice

**Comment by bcheidemann** [comment]
I'd love this too and I'm sure docm77 would appreciate it when they upgrade HC to 1.19 :D

**Comment by Johni0702** [comment]
Released as Bobby 4.0.0 to GitHub, Modrinth and (once approved) CurseForge.
